language: php

php:
  - "7.3"

branches:
  only:
  - master
  - namespaces

matrix:
  include:
    - php: 7.3
      env: deps=highest

mysql:
  database: froxlor010
  username: root
  encoding: utf8

addons:
  apt:
    update: true

service:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS froxlor010'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('fr0xl0r.TravisCI') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u root -pfr0xl0r.TravisCI froxlor010 < install/froxlor.sql
  - mysql -u root -pfr0xl0r.TravisCI -e "CREATE USER 'froxlor010'@'localhost' IDENTIFIED BY 'fr0xl0r.TravisCI';"
  - mysql -u root -pfr0xl0r.TravisCI -e "GRANT ALL ON froxlor010.* TO 'froxlor010'@'localhost';"
#  - phpenv config-rm xdebug.ini

script:
   - ant phpunit

after_success:
    - bash <(curl -s https://codecov.io/bash) -f "build/logs/clover.xml"

notifications:
  irc: "irc.freenode.org#froxlor"
