<?php

/**
 * This file is part of the froxlor project.
 * Copyright (c) 2010 the froxlor Team (see authors).
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, you can also view it online at
 * https://files.froxlor.org/misc/COPYING.txt
 *
 * @copyright  the authors
 * @author     froxlor team <team@froxlor.org>
 * @license    https://files.froxlor.org/misc/COPYING.txt GPLv2
 */

namespace Froxlor\Cron\Mail;

use Froxlor\FileDir;
use Froxlor\FroxlorLogger;
use Froxlor\Settings;

/**
 * Per-domain TLS certificates (SNI) for Dovecot and Postfix.
 *
 * Every domain that has its own Let's Encrypt certificate below
 * system.customer_ssl_path (froxlor writes <domain>.crt, <domain>.key and
 * <domain>_fullchain.pem there) gets a "local_name" block in a separate Dovecot
 * config file and an entry in a Postfix tls_server_sni_maps table. Mail clients
 * are then served the certificate matching the host name they connect to
 * instead of the one central server certificate.
 *
 * The fullchain file is only written for Let's Encrypt certificates. Manually
 * uploaded certificates come without one and are skipped.
 *
 * Both generated files are not part of any of froxlor's config templates, so
 * running the configuration wizard again does not touch them.
 */
class MailSni
{
	/**
	 * Fallback if system.customer_ssl_path is empty, identical to its default.
	 */
	private const DEFAULT_CERT_DIR = '/etc/ssl/froxlor-custom';

	/**
	 * Dovecot includes conf.d/*.conf alphabetically, the "z" makes sure this
	 * file is read after 99-froxlor.conf and 99-froxlor.ssl.conf.
	 */
	private const DOVECOT_SNI_CONF = '/etc/dovecot/conf.d/99-z-froxlor-sni.conf';

	private const POSTFIX_SNI_MAP = '/etc/postfix/froxlor-sni';

	/**
	 * A certificate which expires within this time is not used anymore.
	 */
	private const MIN_VALIDITY_SECONDS = 86400;

	protected FroxlorLogger $logger;

	public function __construct(FroxlorLogger $logger)
	{
		$this->logger = $logger;
	}

	/**
	 * Brings the generated Dovecot/Postfix configuration in line with the
	 * certificates that are currently available. Safe to be called on every
	 * tasks-cron run: nothing is written or reloaded unless the result differs
	 * from what is already in place.
	 */
	public function configure(): void
	{
		if ((int)Settings::Get('mail.sni_enabled') !== 1) {
			$this->disable();
			return;
		}

		// Dovecot and Postfix are handled independently of each other, a server
		// might e.g. run Dovecot together with a different MTA.
		$manageDovecot = Settings::Get('system.mdaserver') === 'dovecot';
		$managePostfix = Settings::Get('system.mtaserver') === 'postfix';

		$dovecot = null;
		if ($manageDovecot) {
			$dovecot = $this->inspectDovecot();
			if ($dovecot === null) {
				$this->logger->logAction(FroxlorLogger::CRON_ACTION, LOG_ERR, 'Mail SNI: `doveconf -n` failed, leaving the Dovecot configuration untouched');
				$manageDovecot = false;
			}
		}
		if (!$manageDovecot && !$managePostfix) {
			return;
		}

		$certDir = $this->certDir();
		$domains = $this->collectValidDomains($certDir, $dovecot['mainHostname'] ?? null);

		$dovecotChanged = $manageDovecot && $this->writeDovecotConf($domains, $certDir, $dovecot['is24']);
		$postfixChanged = $managePostfix && $this->writePostfixMap($domains, $certDir);

		if ($dovecotChanged) {
			$this->reloadDaemon('Dovecot', 'system.mda_reload_command');
		}
		if ($postfixChanged) {
			$this->reloadDaemon('Postfix', 'system.mta_reload_command');
		}
		if ($dovecotChanged || $postfixChanged) {
			$this->logger->logAction(FroxlorLogger::CRON_ACTION, LOG_INFO, 'Per-domain mail SNI configuration updated (' . count($domains) . ' domains)');
		}
	}

	/**
	 * Removes what has been generated by this class once the setting is turned
	 * off. A tls_server_sni_maps which points somewhere else is never touched.
	 */
	private function disable(): void
	{
		$dovecotRemoved = false;
		if (is_file(self::DOVECOT_SNI_CONF)) {
			$dovecotRemoved = @unlink(self::DOVECOT_SNI_CONF);
		}

		$postfixRemoved = false;
		if (is_file(self::POSTFIX_SNI_MAP) || is_file(self::POSTFIX_SNI_MAP . '.db')) {
			// unset the parameter first so Postfix never refers to a removed map
			$unset = $this->postconfGet('tls_server_sni_maps') !== 'hash:' . self::POSTFIX_SNI_MAP
				|| $this->execute('postconf -X tls_server_sni_maps');
			if ($unset) {
				@unlink(self::POSTFIX_SNI_MAP);
				@unlink(self::POSTFIX_SNI_MAP . '.db');
				$postfixRemoved = true;
			} else {
				$this->logger->logAction(FroxlorLogger::CRON_ACTION, LOG_ERR, 'Mail SNI: could not unset tls_server_sni_maps, leaving the Postfix SNI map in place');
			}
		}

		if ($dovecotRemoved) {
			$this->reloadDaemon('Dovecot', 'system.mda_reload_command');
		}
		if ($postfixRemoved) {
			$this->reloadDaemon('Postfix', 'system.mta_reload_command');
		}
		if ($dovecotRemoved || $postfixRemoved) {
			$this->logger->logAction(FroxlorLogger::CRON_ACTION, LOG_INFO, 'Per-domain mail SNI configuration removed');
		}
	}

	/**
	 * Reads the effective Dovecot configuration.
	 *
	 * Dovecot 2.4 renamed the SSL settings (ssl_cert/ssl_key became
	 * ssl_server_cert_file/ssl_server_key_file and no longer use the "<" file
	 * prefix), so the generated file has to use the syntax of the installed
	 * version. froxlor's own Dovecot configuration always contains a top-level
	 * certificate setting, its name tells which syntax is in use. The
	 * certificate itself identifies the host name served by default, which does
	 * not need an entry of its own.
	 *
	 * @return array|null ['is24' => bool, 'mainHostname' => ?string], null if doveconf fails
	 */
	private function inspectDovecot(): ?array
	{
		$output = [];
		if (!$this->execute('doveconf -n', $output)) {
			return null;
		}

		$is24 = false;
		$mainCert = null;
		foreach ($output as $line) {
			// top-level settings only, nested ones (local_name, protocol, ...) are indented
			if (preg_match('/^dovecot_config_version\s*=/', $line)) {
				$is24 = true;
			} elseif ($mainCert === null && preg_match('/^(ssl_cert|ssl_server_cert_file)\s*=\s*<?(.+?)\s*$/', $line, $m)) {
				$is24 = $is24 || $m[1] === 'ssl_server_cert_file';
				$mainCert = $m[2];
			}
		}

		$mainHostname = null;
		if ($mainCert !== null) {
			$info = $this->parseCertificate((string)@file_get_contents($mainCert));
			$mainHostname = $info['subject']['CN'] ?? null;
		}

		return [
			'is24' => $is24,
			'mainHostname' => $mainHostname
		];
	}

	/**
	 * froxlor writes the certificate files of its web-vhosts to
	 * system.customer_ssl_path.
	 */
	private function certDir(): string
	{
		$configured = trim((string)Settings::Get('system.customer_ssl_path'));
		return rtrim($configured !== '' ? $configured : self::DEFAULT_CERT_DIR, '/');
	}

	/**
	 * All domains below $certDir with a usable, consistent set of files, each with
	 * a fingerprint of its fullchain file.
	 *
	 * The domains are taken from the certificate files and deliberately not from
	 * panel_domains/isemaildomain: sub-domains which have a certificate of their
	 * own (e.g. autoconfig., autodiscover., imap., smtp. or webmail.) do not carry
	 * the isemaildomain flag, but mail clients connect to them as well.
	 *
	 * @return array<string, string> fingerprint by domain, sorted by domain
	 */
	private function collectValidDomains(string $certDir, ?string $mainHostname): array
	{
		$domains = [];
		foreach (glob($certDir . '/*.crt') ?: [] as $crtFile) {
			$domain = basename($crtFile, '.crt');
			if ($domain === $mainHostname) {
				continue;
			}
			// the name ends up in generated configuration files, accept host names only
			if (!preg_match('/^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$/i', $domain)) {
				continue;
			}
			$keyFile = $certDir . '/' . $domain . '.key';
			$fullchainFile = $certDir . '/' . $domain . '_fullchain.pem';
			if (!is_file($keyFile) || !is_file($fullchainFile)) {
				continue;
			}
			$fingerprint = $this->checkCertificateSet($crtFile, $keyFile, $fullchainFile, $domain);
			if ($fingerprint !== null) {
				$domains[$domain] = $fingerprint;
			}
		}
		ksort($domains, SORT_STRING);
		return $domains;
	}

	/**
	 * A set of files is only used if
	 *  1. the certificate is still valid for a while,
	 *  2. the private key belongs to the certificate and
	 *  3. the first certificate in the fullchain file is the one for $domain.
	 *
	 * @return string|null fingerprint of the fullchain file if the set is usable, null otherwise
	 */
	private function checkCertificateSet(string $crtFile, string $keyFile, string $fullchainFile, string $domain): ?string
	{
		$crtContent = @file_get_contents($crtFile);
		$keyContent = @file_get_contents($keyFile);
		$fullchainContent = @file_get_contents($fullchainFile);
		if ($crtContent === false || $keyContent === false || $fullchainContent === false) {
			return null;
		}

		$cert = @openssl_x509_read($crtContent);
		if ($cert === false) {
			return null;
		}
		$certInfo = openssl_x509_parse($cert);
		if ($certInfo === false || !isset($certInfo['validTo_time_t']) || $certInfo['validTo_time_t'] < time() + self::MIN_VALIDITY_SECONDS) {
			return null;
		}

		$certPub = @openssl_pkey_get_public($cert);
		$privKey = @openssl_pkey_get_private($keyContent);
		if ($certPub === false || $privKey === false) {
			return null;
		}
		$certPubDetails = openssl_pkey_get_details($certPub);
		$privDetails = openssl_pkey_get_details($privKey);
		if (!isset($certPubDetails['key'], $privDetails['key']) || $certPubDetails['key'] !== $privDetails['key']) {
			return null;
		}

		if (!preg_match('/-----BEGIN CERTIFICATE-----.*?-----END CERTIFICATE-----/s', $fullchainContent, $m)) {
			return null;
		}
		$leafInfo = $this->parseCertificate($m[0]);
		$leafCn = $leafInfo['subject']['CN'] ?? null;
		if ($leafCn === null || strcasecmp($leafCn, $domain) !== 0) {
			return null;
		}

		// The generated files only refer to the certificate files by path. Having the
		// fingerprint in them makes their content change when a certificate is renewed,
		// so Dovecot and Postfix get reloaded instead of serving the old certificate on.
		return substr(hash('sha256', $fullchainContent), 0, 16);
	}

	/**
	 * @return array parsed certificate, empty if $pem is not a valid certificate
	 */
	private function parseCertificate(string $pem): array
	{
		$cert = @openssl_x509_read($pem);
		if ($cert === false) {
			return [];
		}
		$info = openssl_x509_parse($cert);
		return is_array($info) ? $info : [];
	}

	private function buildDovecotConf(array $domains, string $certDir, bool $dovecot24): string
	{
		$content = "# Autogenerated configuration by froxlor.\n";
		$content .= "# Do not manually edit this file as it will be overwritten.\n";
		foreach ($domains as $domain => $fingerprint) {
			$cert = FileDir::makeCorrectFile($certDir . '/' . $domain . '_fullchain.pem');
			$key = FileDir::makeCorrectFile($certDir . '/' . $domain . '.key');
			$content .= "\nlocal_name " . $domain . " {\n";
			$content .= '  # fullchain sha256: ' . $fingerprint . "\n";
			if ($dovecot24) {
				$content .= '  ssl_server_cert_file = ' . $cert . "\n";
				$content .= '  ssl_server_key_file = ' . $key . "\n";
			} else {
				$content .= '  ssl_cert = <' . $cert . "\n";
				$content .= '  ssl_key = <' . $key . "\n";
			}
			$content .= "}\n";
		}
		return $content;
	}

	private function buildPostfixMap(array $domains, string $certDir): string
	{
		$content = "# Autogenerated configuration by froxlor.\n";
		$content .= "# Do not manually edit this file as it will be overwritten.\n";
		foreach ($domains as $domain => $fingerprint) {
			$cert = FileDir::makeCorrectFile($certDir . '/' . $domain . '_fullchain.pem');
			$key = FileDir::makeCorrectFile($certDir . '/' . $domain . '.key');
			$content .= '# ' . $domain . ' fullchain sha256: ' . $fingerprint . "\n";
			// private key first, then the chain; postmap -F merges both files
			$content .= $domain . "\t" . $key . ',' . $cert . "\n";
		}
		return $content;
	}

	/**
	 * @return bool true if the file has been changed and Dovecot still accepts its configuration
	 */
	private function writeDovecotConf(array $domains, string $certDir, bool $dovecot24): bool
	{
		$previous = $this->readFile(self::DOVECOT_SNI_CONF);
		if ($previous === null && $domains === []) {
			return false;
		}
		$new = $this->buildDovecotConf($domains, $certDir, $dovecot24);
		if ($new === $previous) {
			return false;
		}
		if (!$this->atomicWrite(self::DOVECOT_SNI_CONF, $new)) {
			$this->logger->logAction(FroxlorLogger::CRON_ACTION, LOG_ERR, 'Mail SNI: could not write ' . self::DOVECOT_SNI_CONF);
			return false;
		}

		// the new file is live now, make sure Dovecot still accepts its configuration
		if (!$this->execute('doveconf -n')) {
			$this->restoreFile(self::DOVECOT_SNI_CONF, $previous);
			$this->logger->logAction(FroxlorLogger::CRON_ACTION, LOG_ERR, 'Mail SNI: `doveconf -n` reports an error with the new ' . self::DOVECOT_SNI_CONF . ', previous version restored');
			return false;
		}
		return true;
	}

	/**
	 * @return bool true if map and tls_server_sni_maps have been changed and Postfix accepts them
	 */
	private function writePostfixMap(array $domains, string $certDir): bool
	{
		$mapParam = 'hash:' . self::POSTFIX_SNI_MAP;
		$previous = $this->readFile(self::POSTFIX_SNI_MAP);
		$previousParam = $this->postconfGet('tls_server_sni_maps');
		if ($previous === null && $domains === []) {
			return false;
		}
		$new = $this->buildPostfixMap($domains, $certDir);
		if ($new === $previous && $previousParam === $mapParam && is_file(self::POSTFIX_SNI_MAP . '.db')) {
			return false;
		}
		if (!$this->atomicWrite(self::POSTFIX_SNI_MAP, $new)) {
			$this->logger->logAction(FroxlorLogger::CRON_ACTION, LOG_ERR, 'Mail SNI: could not write ' . self::POSTFIX_SNI_MAP);
			return false;
		}

		// postmap -F stores the content of the listed files (key, chain) in the
		// table, Postfix does not need to read them again while serving requests
		if ($this->execute('postmap -F ' . escapeshellarg(self::POSTFIX_SNI_MAP))
			&& $this->execute('postconf -e ' . escapeshellarg('tls_server_sni_maps=' . $mapParam))
			&& $this->execute('postfix check')) {
			return true;
		}

		// restore the parameter first so Postfix never refers to a removed map
		if ($previousParam === '') {
			$this->execute('postconf -X tls_server_sni_maps');
		} else {
			$this->execute('postconf -e ' . escapeshellarg('tls_server_sni_maps=' . $previousParam), $unused, ['$']);
		}
		if ($previous === null) {
			@unlink(self::POSTFIX_SNI_MAP);
			@unlink(self::POSTFIX_SNI_MAP . '.db');
		} else {
			$this->restoreFile(self::POSTFIX_SNI_MAP, $previous);
			$this->execute('postmap -F ' . escapeshellarg(self::POSTFIX_SNI_MAP));
		}
		$this->logger->logAction(FroxlorLogger::CRON_ACTION, LOG_ERR, 'Mail SNI: Postfix did not accept the new SNI map, previous state restored');
		return false;
	}

	private function readFile(string $path): ?string
	{
		$content = @file_get_contents($path);
		return $content === false ? null : $content;
	}

	/**
	 * Puts a file back into the state it had before ($previous === null: it did not exist).
	 */
	private function restoreFile(string $path, ?string $previous): void
	{
		if ($previous === null) {
			@unlink($path);
		} else {
			$this->atomicWrite($path, $previous);
		}
	}

	/**
	 * Writes to a temporary file first so a reader never sees a partial file.
	 */
	private function atomicWrite(string $path, string $content): bool
	{
		$tmp = $path . '.tmp-' . bin2hex(random_bytes(6));
		if (@file_put_contents($tmp, $content, LOCK_EX) === false) {
			@unlink($tmp);
			return false;
		}
		@chmod($tmp, 0644);
		if (!@rename($tmp, $path)) {
			@unlink($tmp);
			return false;
		}
		return true;
	}

	private function postconfGet(string $parameter): string
	{
		$output = [];
		if (!$this->execute('postconf -h ' . escapeshellarg($parameter), $output)) {
			return '';
		}
		return trim(implode('', $output));
	}

	/**
	 * Runs a command and reports whether it succeeded.
	 *
	 * FileDir::safe_exec() neither throws nor reports the exit code unless the
	 * by-reference status variable is initialized with a non-zero value.
	 *
	 * @param string $command
	 * @param array $output output lines of the command
	 * @param array|null $allowedChars passed on to FileDir::safe_exec()
	 *
	 * @return bool true if the exit code is 0
	 */
	private function execute(string $command, &$output = [], ?array $allowedChars = null): bool
	{
		$status = 1;
		$output = FileDir::safe_exec($command, $status, $allowedChars);
		return $status === 0;
	}

	private function reloadDaemon(string $name, string $setting): void
	{
		$cmd = trim((string)Settings::Get($setting));
		if ($cmd === '') {
			$this->logger->logAction(FroxlorLogger::CRON_ACTION, LOG_ERR, 'Mail SNI: no reload command set for ' . $name . ' (' . $setting . ')');
			return;
		}
		$cmdStatus = 1;
		FileDir::safe_exec(escapeshellcmd($cmd), $cmdStatus);
		if ($cmdStatus === 0) {
			$this->logger->logAction(FroxlorLogger::CRON_ACTION, LOG_INFO, $name . ' reloaded');
		} else {
			$this->logger->logAction(FroxlorLogger::CRON_ACTION, LOG_ERR, 'Error while running `' . $cmd . '`: exit code (' . $cmdStatus . ') - please check your system logs');
		}
	}
}
