<?php

/**
 * This file is part of the froxlor project.
 * Copyright (c) 2010 the froxlor Team (see authors).
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, you can also view it online at
 * https://files.froxlor.org/misc/COPYING.txt
 *
 * @copyright  the authors
 * @author     froxlor team <team@froxlor.org>
 * @license    https://files.froxlor.org/misc/COPYING.txt GPLv2
 */

return [
	'languages' => [
		'cz' => '捷克语',
		'de' => '德语',
		'en' => '英语',
		'fr' => '法语',
		'hu' => '匈牙利语',
		'it' => '意大利语',
		'nl' => '荷兰语',
		'pt' => '葡萄牙语',
		'se' => '瑞典语',
		'es' => '西班牙语',
		'ca' => '加泰罗尼亚语',
		'zh_CN' => '简体中文',
	],
	'2fa' => [
		'2fa' => '2FA选项',
		'2fa_enabled' => '启用双因素身份验证（2FA）',
		'2fa_removed' => '成功停用2FA',
		'2fa_added' => '2FA启用成功<br><a class="alert-link" href="%s?page=2fa">查看2FA详情</a>',
		'2fa_add' => '启用2FA',
		'2fa_delete' => '停用2FA',
		'2fa_verify' => '验证代码',
		'2fa_overview_desc' => '在这里，您可以为您的帐户激活双因素身份验证。<br><br>您可以使用验证器应用程序（基于时间的一次性密码/ TOTP），或者让froxlor在每次使用一次性密码成功登录后向您的帐户地址发送电子邮件。',
		'2fa_email_desc' => '您的账户已设置为通过电子邮件使用一次性密码。要停用，请点击"停用2FA"',
		'2fa_ga_desc' => '您的账户已设置为通过验证器应用程序使用基于时间的一次性密码。请使用您选择的验证器应用程序扫描下方的二维码以生成代码。要停用，请点击"停用2FA"',
		'2fa_not_activated' => '未启用双因素身份验证',
		'2fa_not_activated_for_user' => '未为当前用户启用双因素身份验证',
		'type_2fa' => '2FA状态',
	],
	'admin' => [
		'overview' => '概述',
		'ressourcedetails' => '资源详情',
		'systemdetails' => '系统详情',
		'froxlordetails' => 'froxlor详细信息',
		'installedversion' => '安装版本',
		'latestversion' => '最新版本',
		'lookfornewversion' => [
			'clickhere' => '通过网络服务搜索',
			'error' => '读取时出错',
		],
		'resources' => '资源',
		'customer' => '客户',
		'customers' => '客户',
		'customers_list_desc' => '管理您的客户',
		'customer_add' => '创建客户',
		'customer_edit' => '编辑客户',
		'username_default_msg' => '留空以使用自动生成的值',
		'password_default_msg' => '为空时自动生成',
		'domains' => '域名',
		'domain_add' => '创建域名',
		'domain_edit' => '编辑域名',
		'subdomainforemail' => '子域名作为邮件域名',
		'admin' => '管理员',
		'admins' => '管理员',
		'admin_add' => '创建管理员',
		'admin_edit' => '编辑管理员',
		'customers_see_all' => '是否可以访问其他管理员/经销商的资源？',
		'change_serversettings' => '是否可以更改服务器设置？',
		'server' => '服务器',
		'serversettings' => '服务器设置',
		'serversettings_desc' => '管理您的froxlor系统',
		'rebuildconf' => '重新生成配置文件',
		'stdsubdomain' => '标准子域',
		'stdsubdomain_add' => '创建标准子域',
		'phpenabled' => 'PHP已启用',
		'deactivated' => '已停用',
		'deactivated_user' => '停用用户',
		'sendpassword' => '发送密码',
		'ownvhostsettings' => '自定义vHost设置',
		'configfiles' => [
			'serverconfiguration' => '配置',
			'overview' => '概述',
			'wizard' => '向导',
			'distribution' => '系统发行版',
			'service' => '服务',
			'daemon' => '守护进程',
			'http' => 'Web服务器 (HTTP)',
			'dns' => 'DNS服务器',
			'mail' => '邮件服务器 (IMAP/POP3)',
			'smtp' => '邮件服务器 (SMTP)',
			'ftp' => 'FTP服务器',
			'etc' => '其他 (系统)',
			'choosedistribution' => '-- 选择系统发行版 --',
			'chooseservice' => '-- 选择服务 --',
			'choosedaemon' => '-- 选择守护进程 --',
			'statistics' => '统计',
			'compactoverview' => '简洁概述',
			'legend' => '<h3>您将要配置服务/守护进程</h3>',
			'commands' => '<span class="text-danger">命令：</span>这些命令应以root用户身份在Shell中逐行执行。可以安全地复制整个块并粘贴到Shell中。',
			'files' => '<span class="text-danger">配置文件：</span>文本框前的命令应该打开一个带有目标文件的编辑器。只需将内容复制并粘贴到编辑器中，然后保存文件。<br><span class="text-danger">请注意：</span>出于安全原因，MySQL密码尚未被替换。请自行替换"FROXLOR_MYSQL_PASSWORD"或使用下面的JavaScript表单在现场替换。如果您忘记了MySQL密码，可以在"lib/userdata.inc.php"中找到它',
			'importexport' => '导入/导出',
			'finishnote' => '参数文件生成成功。现在以root身份运行以下命令：',
			'description' => '配置系统服务',
			'minihowto' => '在此页面上，您可以查看每个服务的不同配置模板，（重新）配置特定服务（如果需要）或将当前选择导出到JSON文件以在CLI脚本或其他服务器上使用。<br><br><b>请注意</b>，突出显示的服务并不反映您当前的设置，而是显示基于当前设置值的要求/建议。',
			'skipconfig' => '不(重新)配置',
			'recommendednote' => '基于当前系统设置的建议/所需服务',
			'selectrecommended' => '选择推荐',
			'downloadselected' => '导出选定',
		],
		'templates' => [
			'templates' => '邮件模板',
			'template_add' => '添加模板',
			'template_fileadd' => '添加文件模板',
			'template_edit' => '编辑模板',
			'action' => '操作',
			'email' => '邮件和文件模板',
			'subject' => '主题',
			'mailbody' => '邮件正文',
			'createcustomer' => '新客户欢迎邮件',
			'pop_success' => '新邮件账户欢迎邮件',
			'template_replace_vars' => '模板中将被替换的变量：',
			'SALUTATION' => '替换为正确的称呼（姓名或公司）',
			'FIRSTNAME' => '替换为客户的名字。',
			'NAME' => '替换为客户的全名。',
			'COMPANY' => '替换为客户的公司名称。',
			'USERNAME' => '替换为客户的账户用户名。',
			'PASSWORD' => '替换为客户的账户密码。',
			'EMAIL' => '替换为POP3/IMAP账户的地址。',
			'CUSTOMER_NO' => '替换为客户编号。',
			'TRAFFIC' => '替换为分配给客户的流量。',
			'TRAFFICUSED' => '替换为客户已使用的流量。',
			'pop_success_alternative' => '发送至备用地址的新邮件账户欢迎邮件',
			'EMAIL_PASSWORD' => '替换为POP3/IMAP账户密码。',
			'index_html' => '新创建客户目录的索引文件',
			'unconfigured_html' => '未配置/未知域的索引文件',
			'unconfigured_content_fallback' => '此域名需要通过froxlor服务器管理面板进行配置，因为它当前未分配给任何客户。',
			'file_extension' => [
				'description' => '索引文件的文件扩展名长度必须在1到6个字符之间。扩展名只能包含a-z、A-Z和0-9等字符<br><br>默认值：html',
				'title' => '文件模板的文件扩展名',
			],
			'SERVERNAME' => '替换为服务器名称。',
			'CUSTOMER' => '替换为客户的登录名。仅适用于"新创建客户目录的索引文件"',
			'ADMIN' => '替换为管理员的登录名。仅适用于"新创建客户目录的索引文件"',
			'CUSTOMER_EMAIL' => '替换为客户的电子邮件地址。仅适用于"新创建客户目录的索引文件"',
			'ADMIN_EMAIL' => '替换为管理员的电子邮件地址。仅适用于"新创建客户目录的索引文件"',
			'filetemplates' => '文件模板',
			'filecontent' => '文件内容',
			'new_database_by_customer' => '创建数据库时的客户通知',
			'new_ftpaccount_by_customer' => '创建FTP用户时的客户通知',
			'newdatabase' => '新数据库的通知邮件',
			'newftpuser' => '新FTP用户的通知邮件',
			'CUST_NAME' => '客户名称',
			'DB_NAME' => '数据库名称',
			'DB_PASS' => '数据库密码',
			'DB_DESC' => '数据库描述',
			'DB_SRV' => '数据库服务器',
			'PMA_URI' => 'phpMyAdmin的URL（如果有）',
			'USR_NAME' => 'FTP用户名',
			'USR_PASS' => 'FTP密码',
			'USR_PATH' => 'FTP主目录（相对于客户文档根目录）',
			'forgotpwd' => '密码重置的通知邮件',
			'password_reset' => '密码重置的客户通知',
			'trafficmaxpercent' => '当流量配额百分比耗尽时向客户发送通知邮件',
			'MAX_PERCENT' => '替换为发送报告的磁盘使用/流量限制百分比。',
			'USAGE_PERCENT' => '替换为客户已使用的磁盘使用率/流量百分比。',
			'diskmaxpercent' => '当磁盘空间配额百分比耗尽时向客户发送通知邮件',
			'DISKAVAILABLE' => '替换为分配给客户的磁盘使用量。',
			'DISKUSED' => '替换为客户已使用的磁盘空间。',
			'LINK' => '替换为客户密码重置链接。',
			'SERVER_HOSTNAME' => '替换系统主机名（指向froxlor的URL）。',
			'SERVER_IP' => '替换默认服务器IP地址。',
			'SERVER_PORT' => '替换默认服务器端口。',
			'DOMAINNAME' => '替换客户的标准子域（如果没有生成则为空）。',
		],
		'webserver' => 'Web服务器',
		'createzonefile' => '创建域的DNS区域',
		'custombindzone' => '自定义/非托管区域文件',
		'bindzonewarning' => '留空使用默认值<br /><strong class="text-danger">注意：</strong>如果您使用区域文件，则必须手动管理所有子区域所需的所有记录。',
		'ipsandports' => [
			'ipsandports' => 'IP和端口',
			'add' => '添加IP/端口',
			'edit' => '编辑IP/端口',
			'ipandport' => 'IP/端口',
			'ip' => 'IP地址',
			'ipnote' => '<div id="ipnote" class="invalid-feedback">注意：虽然允许使用私有IP地址，但某些功能（如DNS）可能无法正常工作。<br>只有在确定的情况下才使用私有IP地址。</div>',
			'port' => '端口',
			'create_listen_statement' => '创建Listen语句',
			'create_namevirtualhost_statement' => '创建NameVirtualHost语句',
			'create_vhostcontainer' => '创建vHost容器',
			'create_vhostcontainer_servername_statement' => '在vHost容器中创建ServerName语句',
			'enable_ssl' => '这是SSL端口吗？',
			'ssl_cert_file' => 'SSL证书的路径',
			'webserverdefaultconfig' => 'Web服务器默认配置',
			'webserverdomainconfig' => 'Web服务器域名配置',
			'webserverssldomainconfig' => 'Web服务器SSL配置',
			'ssl_key_file' => 'SSL密钥文件的路径',
			'ssl_ca_file' => 'SSL CA证书的路径',
			'default_vhostconf_domain' => '每个域名容器的默认vHost设置',
			'ssl_cert_chainfile' => [
				'title' => 'SSL证书链文件的路径',
				'description' => '大多数情况下是CA_Bundle或类似的，如果您购买了SSL证书，您可能需要设置此选项。',
			],
			'docroot' => [
				'title' => '自定义文档根目录（留空指向froxlor）',
				'description' => '您可以在这里为这个IP/端口组合定义一个自定义的文档根目录（请求的目标位置）。<br /><strong>注意：</strong>请小心您输入的内容！',
			],
			'ssl_paste_description' => '将完整的证书内容粘贴到文本框中',
			'ssl_cert_file_content' => 'SSL证书的内容',
			'ssl_key_file_content' => 'SSL私钥文件的内容',
			'ssl_ca_file_content' => 'SSL CA文件的内容（可选）',
			'ssl_ca_file_content_desc' => '<br /><br />客户端身份验证，只有当您知道它是什么时才设置它。',
			'ssl_cert_chainfile_content' => '证书链文件的内容（可选）',
			'ssl_cert_chainfile_content_desc' => '<br /><br />大多数情况下是CA_Bundle或类似的，如果您购买了SSL证书，您可能需要设置此选项。',
			'ssl_default_vhostconf_domain' => '每个域名容器的默认SSL vHost设置',
		],
		'memorylimitdisabled' => '已禁用',
		'valuemandatory' => '此值是必需的',
		'valuemandatorycompany' => '必须填写"姓名"和"名字"或"公司"',
		'serversoftware' => '服务器软件',
		'phpversion' => 'PHP版本',
		'mysqlserverversion' => 'MySQL服务器版本',
		'webserverinterface' => 'Web服务器接口',
		'accountsettings' => '帐号设置',
		'panelsettings' => '面板设置',
		'systemsettings' => '系统设置',
		'webserversettings' => 'Web服务器设置',
		'mailserversettings' => '邮件服务器设置',
		'nameserversettings' => 'DNS服务器设置',
		'updatecounters' => '重新计算资源使用情况',
		'subcanemaildomain' => [
			'never' => '从不',
			'choosableno' => '可选，默认为否',
			'choosableyes' => '可选，默认为是',
			'always' => '始终',
		],
		'wipecleartextmailpwd' => '清除明文密码',
		'webalizersettings' => 'Webalizer设置',
		'webalizer' => [
			'normal' => '正常',
			'quiet' => '安静',
			'veryquiet' => '无输出',
		],
		'domain_nocustomeraddingavailable' => '当前无法添加域名。您首先需要至少添加一个客户。',
		'loggersettings' => '日志设置',
		'logger' => [
			'normal' => '正常',
			'paranoid' => '详细',
		],
		'emaildomain' => '邮件域名',
		'email_only' => '仅限邮件',
		'wwwserveralias' => '添加"www." ServerAlias',
		'subject' => '主题',
		'recipient' => '收件人',
		'message' => '编写消息',
		'text' => '消息',
		'sslsettings' => 'SSL设置',
		'specialsettings_replacements' => '您可以使用以下变量：<br/><code>{DOMAIN}</code>、<code>{DOCROOT}</code>、<code>{CUSTOMER}</code>、<code>{IP}</code>、<code>{PORT}</code>、<code>{SCHEME}</code>、<code>{FPMSOCKET}</code>（如果适用）<br/>',
		'antispam_settings' => '反垃圾邮件设置',
		'caneditphpsettings' => '可以更改PHP相关的域名设置吗？',
		'allips' => '所有IP',
		'awstatssettings' => 'AWstats设置',
		'domain_dns_settings' => '域名DNS设置',
		'activated' => '已激活',
		'statisticsettings' => '统计设置',
		'or' => '或',
		'sysload' => '系统负载',
		'noloadavailable' => '不可用',
		'nouptimeavailable' => '不可用',
		'nosubject' => '（无主题）',
		'security_settings' => '安全选项',
		'know_what_youre_doing' => '只有当您知道您在做什么的时候，才能更改！',
		'show_version_login' => [
			'title' => '登录时显示froxlor版本',
			'description' => '在登录页面的页脚中显示froxlor版本',
		],
		'show_version_footer' => [
			'title' => '在页脚中显示froxlor版本',
			'description' => '在其余页面的页脚中显示froxlor版本',
		],
		'froxlor_graphic' => [
			'title' => 'froxlor的标题图片',
			'description' => '标题中应显示什么图片',
		],
		'phpsettings' => [
			'title' => 'PHP配置',
			'description' => '简短描述',
			'actions' => '操作',
			'activedomains' => '正在用于域名',
			'notused' => '配置未使用',
			'editsettings' => '更改PHP设置',
			'addsettings' => '创建新的PHP设置',
			'viewsettings' => '查看PHP设置',
			'phpinisettings' => 'php.ini设置',
			'addnew' => '创建新的PHP配置',
			'binary' => 'PHP二进制文件',
			'fpmdesc' => 'PHP-FPM配置',
			'file_extensions' => '文件扩展名',
			'file_extensions_note' => '（不带点，以空格分隔）',
			'enable_slowlog' => '启用慢日志（每个域名）',
			'request_terminate_timeout' => '请求终止超时',
			'request_slowlog_timeout' => '请求慢日志超时',
			'activephpconfigs' => '正在使用的PHP配置',
			'pass_authorizationheader' => '将HTTP AUTH BASIC/DIGEST头从Apache传递到PHP',
		],
		'misc' => '杂项',
		'fpmsettings' => [
			'addnew' => '创建新的PHP版本',
			'edit' => '更改PHP版本'
		],
		'phpconfig' => [
			'template_replace_vars' => '配置中将被替换的变量',
			'pear_dir' => '将被替换为pear目录的全局设置。',
			'open_basedir_c' => '将插入一个;(分号)以在设置时注释/禁用open_basedir',
			'open_basedir' => '将被替换为域名的open_basedir设置。',
			'tmp_dir' => '将被替换为域名的临时目录。',
			'open_basedir_global' => '将被替换为路径的全局值，该路径将附加到open_basedir（请参阅Web服务器设置）。',
			'customer_email' => '将被替换为拥有此域名的客户的电子邮件地址。',
			'admin_email' => '将被替换为拥有此域名的管理员的电子邮件地址。',
			'domain' => '将被替换为域名。',
			'customer' => '将被替换为拥有此域名的客户的登录名。',
			'admin' => '将被替换为拥有此域名的管理员的登录名。',
			'docroot' => '将被替换为域名的文档根目录。',
			'homedir' => '将被替换为客户的主目录。',
		],
		'expert_settings' => '专家设置！',
		'mod_fcgid_starter' => [
			'title' => '此域名的PHP进程（留空使用默认值）',
		],
		'phpserversettings' => 'PHP设置',
		'mod_fcgid_maxrequests' => [
			'title' => '此域名的最大PHP请求数（留空使用默认值）',
		],
		'spfsettings' => '域名SPF设置',
		'specialsettingsforsubdomains' => '将特殊设置应用于所有子域名（*.example.com）',
		'accountdata' => '账户数据',
		'contactdata' => '联系数据',
		'servicedata' => '服务数据',
		'newerversionavailable' => 'froxlor有新版本可用。',
		'newerversiondetails' => '是否立即更新到版本<b>%s</b>？<br/>（您的当前版本为：%s）',
		'extractdownloadedzip' => '解压下载的归档文件 "%s"？',
		'cron' => [
			'cronsettings' => '定时任务设置',
			'add' => '添加定时任务',
		],
		'cronjob_edit' => '编辑定时任务',
		'warning' => '请注意！',
		'lastlogin_succ' => '上次登录',
		'ftpserver' => 'FTP服务器',
		'ftpserversettings' => 'FTP服务器设置',
		'webserver_user' => 'Web服务器用户名',
		'webserver_group' => 'Web服务器组名',
		'perlenabled' => 'Perl已启用',
		'fcgid_settings' => 'FCGID',
		'mod_fcgid_user' => '用于FCGID的本地用户（froxlor vHost）',
		'mod_fcgid_group' => '用于FCGID的本地组（froxlor vHost）',
		'perl_settings' => 'Perl/CGI',
		'notgiven' => '[未指定]',
		'store_defaultindex' => '将默认索引文件存储到客户文档根目录',
		'phpfpm_settings' => 'PHP-FPM',
		'traffic' => '流量',
		'traffic_sub' => '流量使用详情',
		'domaintraffic' => '域名',
		'customertraffic' => '客户',
		'assignedmax' => '已分配/最大',
		'usedmax' => '已用/最大',
		'used' => '已用',
		'speciallogwarning' => '<div id="speciallogfilenote" class="invalid-feedback">警告：更改此设置将丢失此域名的所有旧统计数据。</div>',
		'speciallogfile' => [
			'title' => '单独的日志文件',
			'description' => '启用此选项可获取此域名的单独访问日志文件',
		],
		'domain_editable' => [
			'title' => '允许编辑域名',
			'desc' => '如果设置为是，则允许客户更改多个域名设置。<br />如果设置为否，则客户不能更改任何内容。',
		],
		'writeaccesslog' => [
			'title' => '写入访问日志',
			'description' => '启用此选项可获取此域名的访问日志文件',
		],
		'writeerrorlog' => [
			'title' => '写入错误日志',
			'description' => '启用此选项可获取此域名的错误日志文件',
		],
		'phpfpm.ininote' => '并不是所有您想要定义的值都可以在PHP-FPM池配置中使用',
		'phpinfo' => 'PHP 信息',
		'selectserveralias' => '域名的 ServerAlias 值',
		'selectserveralias_desc' => '选择froxlor是否应创建通配符条目（*.domain.tld）、WWW别名（www.domain.tld）或根本不创建别名',
		'show_news_feed' => [
			'title' => '在管理员仪表板上显示新闻源',
			'description' => '启用此功能可以在您的仪表板上显示官方froxlor新闻源（https://inside.froxlor.org/news/），并且永远不会错过重要信息或发布公告。',
		],
		'cronsettings' => '定时任务设置',
		'integritycheck' => '数据库完整性检查',
		'integrityname' => '名称',
		'integrityresult' => '结果',
		'integrityfix' => '自动修复问题',
		'customer_show_news_feed' => '在客户控制面板上显示新闻源',
		'customer_news_feed_url' => [
			'title' => '使用自定义RSS源',
			'description' => '指定一个自定义的RSS源，将显示给您的客户在他们的仪表板上。<br /><small>将此留空以使用官方froxlor新闻源（https://inside.froxlor.org/news/）。</small>',
		],
		'movetoadmin' => '移动客户',
		'movecustomertoadmin' => [
			'title' => '将客户移动到选定的管理员/经销商',
			'description' => '留空则不更改。<br />如果所需的管理员没有出现在列表中，则已达到其客户数量限制。',
		],
		'note' => '注意',
		'mod_fcgid_umask' => [
			'title' => 'Umask（默认值：022）',
		],
		'apcuinfo' => 'APCu信息',
		'opcacheinfo' => 'OPcache信息',
		'letsencrypt' => [
			'title' => '使用Let\'s Encrypt',
			'description' => '从<a href="https://letsencrypt.org">Let\'s Encrypt</a>获取免费证书。证书将自动创建和续订。<br><strong class="text-danger">注意：</strong>如果启用了通配符，此选项将自动禁用。',
		],
		'autoupdate' => '自动更新',
		'server_php' => 'PHP',
		'dnsenabled' => '启用DNS编辑器',
		'froxlorvhost' => 'froxlor VirtualHost设置',
		'hostname' => '主机名',
		'memory' => '内存使用',
		'webserversettings_ssl' => 'Web服务器SSL设置',
		'domain_hsts_maxage' => [
			'title' => 'HTTP严格传输安全（HSTS）',
			'description' => '指定安全传输标头的最大有效期<br>值<i>0</i>将禁用域名的HSTS。大多数用户将值设置为<i>31536000</i>（一年）。',
		],
		'domain_hsts_incsub' => [
			'title' => '包含所有子域的HSTS',
			'description' => '可选的"includeSubDomains"指令（如果存在）向用户代理发出信号，表明HSTS策略适用于此HSTS主机以及主机域名的任何子域。',
		],
		'domain_hsts_preload' => [
			'title' => '在HSTS预加载列表中包含域名',
			'description' => '如果您希望将此域名包含在Chrome维护的<a href="https://hstspreload.org/" target="_blank">HSTS预加载列表</a>中（并被Firefox和Safari使用），请启用此选项。<br>从您的站点发送preload指令可能会产生永久性后果，并阻止用户访问您的站点及其任何子域。<br>在发送带有"preload"的标头之前，请阅读<a href="https://hstspreload.org/#removal" target="_blank">https://hstspreload.org/#removal</a>上的详细信息。',
		],
		'domain_ocsp_stapling' => [
			'title' => 'OCSP装订',
			'description' => '有关OCSP装订的详细说明，请参阅<a target="_blank" href="https://en.wikipedia.org/wiki/OCSP_stapling">维基百科</a>',
			'nginx_version_warning' => '<br /><strong class="text-danger">警告：</strong>OCSP装订需要Nginx 1.3.7或更高版本。如果您的版本较旧，启用OCSP装订时Web服务器将无法正确启动！',
		],
		'domain_http2' => [
			'title' => 'HTTP/2支持',
			'description' => '有关HTTP/2的详细说明，请参阅<a target="_blank" href="https://en.wikipedia.org/wiki/HTTP/2">维基百科</a>',
		],
		'domain_http3' => [
			'title' => 'HTTP/3支持',
			'description' => '有关HTTP/3的详细说明，请参阅<a target="_blank" href="https://en.wikipedia.org/wiki/HTTP/3">维基百科</a>',
			'nginx_version_warning' => '<br /><strong class="text-danger">警告：</strong>HTTP/3需要Nginx 1.25.0或更高版本以及SSL协议TLSv1.3。如果您的版本较旧，启用HTTP/3时Web服务器将无法正确启动！',
		],
		'testmail' => 'SMTP测试',
		'phpsettingsforsubdomains' => '将PHP配置应用于所有子域名：',
		'plans' => [
			'name' => '计划名称',
			'description' => '描述',
			'last_update' => '最后更新',
			'plans' => '托管计划',
			'plan_details' => '计划详情',
			'add' => '添加新计划',
			'edit' => '编辑计划',
			'use_plan' => '应用计划',
		],
		'notryfiles' => [
			'title' => '不自动生成try_files',
			'description' => '如果您想在特殊设置中指定一个自定义的try_files指令（例如一些WordPress插件需要），请在此处选择是。',
		],
		'logviewenabled' => '启用访问/错误日志查看',
		'novhostcontainer' => '<br><br><small class="text-danger">没有任何IP和端口启用了"创建vHost容器"选项，许多设置将不可用</small>',
		'ownsslvhostsettings' => '自定义SSL vHost设置',
		'domain_override_tls' => '覆盖系统TLS设置',
		'domain_override_tls_addinfo' => '<br /><span class="text-danger">仅在"覆盖系统TLS设置"设置为"是"时使用</span>',
		'domain_sslenabled' => '启用SSL',
		'domain_honorcipherorder' => '遵循（服务器）密码顺序，默认<strong>否</strong>',
		'domain_sessiontickets' => '启用TLS会话票据（RFC 5077），默认<strong>是</strong>',
		'domain_sessionticketsenabled' => [
			'title' => '启用全局TLS会话票据的使用',
			'description' => '默认<strong>是</strong><br>需要Apache 2.4.11+或Nginx 1.5.9+',
		],
		'domaindefaultalias' => '新域名的默认ServerAlias值',
		'smtpsettings' => 'SMTP设置',
		'smtptestaddr' => '发送测试邮件至',
		'smtptestnote' => '请注意，下面的值反映了您当前的设置，只能在那里进行调整（请参阅右上角的链接）',
		'smtptestsend' => '发送测试邮件',
		'mysqlserver' => [
			'mysqlserver' => 'MySQL服务器',
			'dbserver' => '数据库服务器',
			'caption' => '说明',
			'host' => '主机名/IP',
			'port' => '端口',
			'user' => '特权用户',
			'add' => '添加新的MySQL服务器',
			'edit' => '编辑MySQL服务器',
			'password' => '已验证的用户密码',
			'password_emptynochange' => '新密码，留空不更改',
			'allowall' => [
				'title' => '允许所有现有客户使用此服务器',
				'description' => '如果要将此数据库服务器的使用权限授予所有现有客户，使他们能够在其上添加数据库，请设置为"true"。此设置不是永久性的，但可以多次运行。',
			],
			'testconn' => '保存时测试连接',
			'ssl' => '使用SSL连接到数据库服务器',
			'ssl_cert_file' => 'SSL证书颁发机构的文件路径',
			'verify_ca' => '启用服务器SSL证书验证',
		],
		'settings_importfile' => '选择导入文件',
		'documentation' => '文档',
		'adminguide' => '管理员指南',
		'userguide' => '用户指南',
		'apiguide' => 'API指南',
		'domain_duplicate' => '重复域名',
		'domain_duplicate_named' => '重复%s',
		'backups' => [
			'backups' => '备份',
		],
		'emaildomainwarning' => '<div id="emaildomainnote" class="invalid-feedback">警告：更改此设置将永久删除所有现有的电子邮件地址和账户。</div>',
	],
	'apcuinfo' => [
		'clearcache' => '清除APCu缓存',
		'generaltitle' => '常规缓存信息',
		'version' => 'APCu版本',
		'phpversion' => 'PHP版本',
		'host' => 'APCu主机',
		'sharedmem' => '共享内存',
		'sharedmemval' => '%d个段，具有%s（%s内存）',
		'start' => '开始时间',
		'uptime' => '运行时间',
		'upload' => '文件上传支持',
		'cachetitle' => '缓存信息',
		'cvar' => '缓存的变量',
		'hit' => '命中',
		'miss' => '未命中',
		'reqrate' => '请求率（命中，未命中）',
		'creqsec' => '缓存请求/秒',
		'hitrate' => '命中率',
		'missrate' => '未命中率',
		'insrate' => '插入率',
		'cachefull' => '缓存满计数',
		'runtime' => '运行时设置',
		'memnote' => '内存使用',
		'total' => '总计',
		'free' => '空闲',
		'used' => '已用',
		'hitmiss' => '命中和未命中',
		'detailmem' => '详细的内存使用和碎片',
		'fragment' => '碎片化',
		'nofragment' => '无碎片',
		'fragments' => '碎片',
	],
	'apikeys' => [
		'no_api_keys' => '未找到API密钥',
		'key_add' => '添加新密钥',
		'apikey_removed' => 'ID为#%s的API密钥已成功删除',
		'apikey_added' => '已成功生成新的API密钥',
		'clicktoview' => '点击查看',
		'allowed_from' => '允许来源',
		'allowed_from_help' => '以逗号分隔的IP地址/网络列表。<br>默认为空（允许所有人）。',
		'valid_until' => '有效期至',
		'valid_until_help' => '有效日期，格式为YYYY-MM-DDThh:mm',
	],
	'changepassword' => [
		'old_password' => '旧密码',
		'new_password' => '新密码',
		'new_password_confirm' => '确认密码',
		'new_password_ifnotempty' => '新密码（留空则不更改）',
		'also_change_ftp' => '同时更改主FTP账户的密码',
		'also_change_stats' => '同时更改统计页面的密码',
		'also_change_global_mysql' => '同时更改全局MySQL账户的密码',
	],
	'cron' => [
		'cronname' => '定时任务名称',
		'lastrun' => '上次运行',
		'interval' => '间隔',
		'isactive' => '已启用',
		'description' => '描述',
		'changewarning' => '更改这些值可能会对froxlor及其自动化任务的行为产生负面影响。<br />请仅在您确定知道自己在做什么的情况下更改此处的值。',
	],
	'crondesc' => [
		'cron_unknown_desc' => '未给出描述',
		'cron_tasks' => '生成配置文件',
		'cron_legacy' => '旧版定时任务',
		'cron_traffic' => '流量计算',
		'cron_usage_report' => 'Web和流量报告',
		'cron_mailboxsize' => '邮箱容量计算',
		'cron_letsencrypt' => 'Let\'s Encrypt证书更新',
		'cron_export' => '处理数据导出作业',
		'cron_backup' => '处理系统和客户备份作业',
	],
	'cronjob' => [
		'cronjobsettings' => '定时任务设置',
		'cronjobintervalv' => '运行间隔值',
		'cronjobinterval' => '运行间隔',
	],
	'cronjobs' => [
		'notyetrun' => '尚未运行',
	],
	'cronmgmt' => [
		'minutes' => '分钟',
		'hours' => '小时',
		'days' => '天',
		'weeks' => '周',
		'months' => '个月',
	],
	'customer' => [
		'documentroot' => '主目录',
		'name' => '名称',
		'firstname' => '名字',
		'lastname' => '姓氏',
		'company' => '公司',
		'nameorcompany_desc' => '名字/姓氏或公司是必需的',
		'street' => '街道',
		'zipcode' => '邮政编码',
		'city' => '城市',
		'phone' => '电话',
		'fax' => '传真',
		'email' => '邮箱',
		'customernumber' => '客户ID',
		'diskspace' => '网站空间',
		'traffic' => '流量',
		'mysqls' => 'MySQL数据库',
		'emails' => '邮箱地址',
		'accounts' => '邮箱账户',
		'forwarders' => '邮件转发',
		'ftps' => 'FTP账户',
		'subdomains' => '子域名',
		'domains' => '域名',
		'mib' => 'MiB',
		'gib' => 'GiB',
		'title' => '标题',
		'country' => '国家',
		'email_quota' => '邮箱配额',
		'email_imap' => '邮箱IMAP',
		'email_pop3' => '邮箱POP3',
		'sendinfomail' => '通过邮箱发送数据给我',
		'generated_pwd' => '密码建议',
		'usedmax' => '已用/最大',
		'services' => '服务',
		'letsencrypt' => [
			'title' => '使用Let\'s Encrypt',
			'description' => '从<a href="https://letsencrypt.org">Let\'s Encrypt</a>获取免费证书。证书将自动创建和续订。',
		],
		'selectserveralias_addinfo' => '此选项可在编辑域名时设置。其初始值继承自父域名。',
		'total_diskspace' => '总磁盘空间',
		'mysqlserver' => '可用的MySQL服务器',
	],
	'diskquota' => '配额',
	'antispam' => [
		'config_file' => [
			'title' => '反垃圾邮件设置文件',
			'description' => '请指定邮件反垃圾邮件规则的文件名',
		],
		'reload_command' => [
			'title' => 'Milter重启命令',
			'description' => '请指定rspamd服务的重启命令',
		],
		'activated' => [
			'title' => '启用反垃圾邮件？',
			'description' => '您想使用rspamd作为反垃圾邮件服务吗？',
		],
		'dkim_keylength' => [
			'title' => 'DKIM密钥长度',
			'description' => '注意：更改仅适用于新密钥<br/><br/>需要域名的特定DNS条目。如果您不使用名称服务器功能，则必须手动管理这些条目。',
		],
		'spam_tag_level' => [
			'title' => '垃圾邮件标记级别',
			'description' => '将邮件标记为垃圾邮件所需的分数<br/>默认值：7.0'
		],
		'rewrite_subject' => [
			'title' => '重写主题',
			'description' => '是否在邮件主题中添加<strong>***SPAM***</strong>（如适用）',
		],
		'spam_kill_level' => [
			'title' => '垃圾邮件拦截级别',
			'description' => '完全丢弃邮件所需的分数<br/>默认值：14.0'
		],
		'bypass_spam' => [
			'title' => '绕过垃圾邮件过滤器',
			'description' => '启用以绕过/禁用此地址的垃圾邮件过滤。<br/>默认值：否'
		],
		'policy_greylist' => [
			'title' => '使用灰名单',
			'description' => '传入的邮件将受到<a href="https://en.wikipedia.org/wiki/Greylisting_(email)" target="_blank">灰名单</a>保护。<br/>默认值：是'
		],
		'required_spf_dns' => '需要SPF DNS条目',
		'required_dmarc_dns' => '需要DMARC DNS条目',
		'required_dkim_dns' => '需要DKIM DNS条目',
		'default_select' => [
			'on_changeable' => '启用，可调整',
			'off_changeable' => '停用，可调整',
			'on_unchangeable' => '启用，不可调整',
			'off_unchangeable' => '停用，不可调整',
		],
		'default_bypass_spam' => [
			'title' => '绕过垃圾邮件过滤器默认值',
			'description' => '新邮件账户是否默认启用"绕过垃圾邮件过滤器"，以及此设置是否可由客户调整。<br/>默认值：停用，可调整'
		],
		'default_spam_rewrite_subject' => [
			'title' => '重写主题默认值',
			'description' => '新邮件账户是否默认启用"重写主题"，以及此设置是否可由客户调整。<br/>默认值：启用，可调整'
		],
		'default_policy_greylist' => [
			'title' => '使用灰名单默认值',
			'description' => '新邮件账户是否默认启用"使用灰名单"，以及此设置是否可由客户调整。<br/>默认值：启用，可调整'
		],
	],
	'dns' => [
		'destinationip' => '域名IP地址',
		'standardip' => '服务器标准IP',
		'a_record' => 'A记录（IPv6可选）',
		'cname_record' => 'CNAME记录',
		'mxrecords' => '定义MX记录',
		'standardmx' => '服务器标准MX记录',
		'mxconfig' => '自定义MX记录',
		'priority10' => '优先级10',
		'priority20' => '优先级20',
		'txtrecords' => '定义TXT记录',
		'txtexample' => '示例（SPF条目）：<br />v=spf1 ip4:xxx.xxx.xx.0/23 -all',
		'howitworks' => '在这里您可以管理域名的DNS记录。请注意，froxlor将自动为您生成NS/MX/A/AAAA记录。自定义条目优先，只有缺失的条目才会自动生成。',
		'nis2note' => [
			'title' => 'NIS2信息',
			'content' => 'DNS托管/权威DNS服务可能被视为一种数字服务，根据<strong>EU-NIS2</strong>，其安全性和报告义务有所增加。请检查您的设置是否受NIS2影响以及需要采取哪些措施。'
		],
	],
	'dnseditor' => [
		'edit' => '编辑DNS',
		'records' => '记录',
		'notes' => [
			'A' => '32位IPv4地址，用于将主机名映射到主机的IP地址。',
			'AAAA' => '128位IPv6地址，用于将主机名映射到主机的IP地址。',
			'CAA' => 'CAA资源记录允许DNS域名持有者指定一个或多个授权为该域名颁发证书的证书颁发机构（CA）。<br>结构：<code>flag tag[issue|issuewild|iodef|contactmail|contactphone] value</code><br>示例：<code>0 issue "ca.example.net"<br>0 iodef "mailto:security@example.com"</code>',
			'CNAME' => '域名的别名，DNS查找将通过使用新名称重试查找来继续。仅适用于子域名！',
			'DNAME' => '为域名树的整个子树创建别名',
			'LOC' => '域名的地理位置信息。<br>结构：<code>( d1 [m1 [s1]] {"N"|"S"} d2 [m2 [s2]] {"E"|"W"} alt["m"] [siz["m"] [hp["m"] [vp["m"]]]] )</code><br>描述：<code>d1: [0..90] (纬度度数), d2: [0..180] (经度度数), m1,m2: [0..59] (分), s1,s2: [0..59.999] (秒), alt: 海拔高度(米)</code><br>示例：<code>52 22 23.000 N 4 53 32.000 E -2.00m 0.00m 10000m 10m</code>',
			'MX' => '邮件交换记录，将域名映射到该域的邮件服务器。<br>示例：<code>10 mail.example.com</code><br>注：对于优先级，请使用上面的字段',
			'NS' => '委派DNS区域以使用给定的权威名称服务器。',
			'RP' => '负责人记录<br>结构：<code>邮箱[将@替换为点] txt-record-name</code><br>示例：<code>team.froxlor.org. froxlor.org.</code>',
			'SRV' => '服务位置记录，用于较新的协议，而不是创建特定于协议的记录，如MX。<br>结构：<code>优先级 权重 端口 目标</code><br>示例：<code>0 5 5060 sipserver.example.com.</code><br>注：对于优先级，请使用上面的字段',
			'SSHFP' => 'SSHFP资源记录用于在DNS中发布安全外壳（SSH）密钥指纹。<br>结构：<code>算法 类型 指纹</code><br>算法：<code>0：保留，1：RSA，2：DSA，3：ECDSA，4：Ed25519，6：Ed448</code><br>类型：<code>0：保留，1：SHA-1，2：SHA-256</code><br>示例：<code>2 1 123456789abcdef67890123456789abcdef67890</code>',
			'TLSA' => 'TLSA（TLS认证）记录用于发布TLS/SSL证书的指纹。它通常用于DANE。<br>只有在您的域名上启用了DNSSEC，TLSA记录才能被信任。<br>结构：<code>使用 选择器 类型 指纹</code><br>证书用法：<code>0：PKIX-T，1：PKIX-EE，2：DANE-TA，3：DANE-EE</code><br>选择器：<code>0：使用完整证书，1：使用主题公钥</code><br>匹配类型：<code>0：完整：无哈希，1：SHA-256哈希，2：SHA-512哈希</code><br>示例：<code>3 1 1 123456789abcdef67890123456789abcdef123456789abcdef123456789abcde</code>',
			'TXT' => '自由定义的描述性文本。'
		]
	],
	'domain' => [
		'openbasedirpath' => 'OpenBasedir路径',
		'inherited' => '与父域名相同',
		'docroot' => '从上方字段开始的路径',
		'homedir' => '主目录',
		'docparent' => '上方字段中路径的父目录',
		'ssl_certificate_placeholder' => '---- 开始证书----' . PHP_EOL . '[...]' . PHP_EOL . '----结束证书----',
		'ssl_key_placeholder' => '---- 开始RSA私钥----' . PHP_EOL . '[...]' . PHP_EOL . '-----结束RSA私钥-----',
	],
	'domains' => [
		'description' => '在这里，您可以创建（子）域并更改其路径。<br />每次更改后，系统都需要一些时间来应用新设置。',
		'domainsettings' => '域设置',
		'domainname' => '域名',
		'subdomain_add' => '创建子域名',
		'subdomain_edit' => '编辑（子）域',
		'wildcarddomain' => '创建为通配符域？',
		'aliasdomain' => '别名域名',
		'noaliasdomain' => '没有别名域',
		'hasaliasdomains' => '具有别名域',
		'statstics' => '使用统计',
		'isassigneddomain' => '已分配域',
		'add_date' => '添加至froxlor',
		'registration_date' => '添加到注册表',
		'topleveldomain' => '顶级域名',
		'associated_with_domain' => '关联',
		'aliasdomains' => '别名域名',
		'redirectifpathisurl' => '重定向代码（默认：空）',
		'redirectifpathisurlinfo' => '仅当您输入URL作为路径时才需要选择其中之一<br/><strong class="text-danger">注意：</strong>仅当给定路径是URL时才应用更改。',
		'ipandport_multi' => [
			'title' => 'IP地址',
			'description' => '为域名指定一个或多个IP地址。<br /><br /><div class="text-danger">注意：当域名配置为另一个域名的<strong>别名域名</strong>时，无法更改IP地址。</div>',
		],
		'ipandport_ssl_multi' => [
			'title' => 'SSL IP地址',
		],
		'ssl_redirect' => [
			'title' => 'SSL重定向',
			'description' => '此选项为非SSL虚拟主机创建重定向，以便将所有请求重定向到SSL虚拟主机。<br /><br />例如，对<strong>http</strong>://domain.tld/的请求将重定向到<strong>https</strong>://domain.tld/',
		],
		'serveraliasoption_wildcard' => '通配符（*.domain.tld）',
		'serveraliasoption_www' => '万维网（www.domain.tld）',
		'serveraliasoption_none' => '没有别名',
		'domain_import' => '导入域名',
		'import_separator' => '分隔符',
		'import_offset' => '偏移',
		'import_file' => 'CSV文件',
		'import_description' => '有关导入文件结构和如何成功导入的详细信息，请访问<a href="https://docs.froxlor.org/latest/admin-guide/domain-import/" target="_blank" class="alert-link">https://docs.froxlor.org/latest/admin-guide/domain-import/</a>',
		'ssl_redirect_temporarilydisabled' => '<br>SSL重定向在生成新的Let\'s Encrypt证书时暂时停用。它将在生成证书后再次激活。',
		'termination_date' => '终止日期',
		'termination_date_overview' => '终止于',
		'ssl_certificates' => 'SSL证书',
		'ssl_certificate_removed' => '已成功删除ID为#%s的证书',
		'ssl_certificate_error' => '读取域名%s的证书时出错',
		'no_ssl_certificates' => '没有配置SSL证书的域名',
		'isaliasdomainof' => '是%s的别名域',
		'isbinddomain' => '创建DNS区域',
		'dkimenabled' => '已启用DKIM',
		'openbasedirenabled' => '启用Openbasedir限制',
		'hsts' => '启用HSTS',
		'aliasdomainid' => '别名域ID',
		'nodomainsassignedbyadmin' => '您的帐户当前没有分配（活动）域。如果您认为这是错误的，请与管理员联系。',
		'email_only' => '仅限邮件',
	],
	'emails' => [
		'description' => '在这里，您可以创建和更改您的电子邮件地址。<br />账户就像你家门口的信箱，如果有人给你发了邮件，它就会被放进账户里。<br /><br />要下载您的电子邮件，请在邮件程序中使用以下设置：（斜体的数据<i></i>必须更改为您键入的等效值！）<br />主机名：<b><i>域名</i></b><br />用户名：<b><i>帐户名称/电子邮件地址</i></b><br />密码：<b><i>您选择的密码</i></b>',
		'emailaddress' => '电子邮件地址',
		'emails_add' => '创建电子邮件地址',
		'emails_edit' => '编辑电子邮件地址',
		'catchall' => '全局收件箱',
		'iscatchall' => '定义为全局收件箱？',
		'account' => '账户',
		'account_add' => '创建帐户',
		'account_delete' => '删除帐户',
		'from' => '发件人',
		'to' => '收件人',
		'forwarders' => '邮件转发',
		'forwarder_add' => '添加邮件转发',
		'alternative_emailaddress' => '备用电子邮件地址',
		'quota' => '配额',
		'noquota' => '无配额',
		'updatequota' => '更新配额',
		'quota_edit' => '更改电子邮件地址',
		'noemaildomainaddedyet' => '您的帐户中还没有（电子邮件-）域。',
		'back_to_overview' => '返回到域名概览',
		'accounts' => '邮箱账户',
		'emails' => '邮箱',
		'senders' => '允许的发件人',
		'sender_add' => '添加允许的发件人',
		'foreign_sender' => '允许的（外部）发送方',
		'allowed_sender_info' => '使用允许的<strong>发件人</strong>，您允许现有的电子邮件帐户发送具有不同发件人地址的电子邮件。<br><strong>重要：</strong>此处输入的地址/通配符域不会自动成为邮箱-它仅用作附加的允许发件人标识符。',
	],
	'error' => [
		'error' => '错误',
		'directorymustexist' => '目录%s必须存在。请使用FTP客户端创建它。',
		'filemustexist' => '文件%s必须存在。',
		'allresourcesused' => '你已经用尽了所有的资源。',
		'domains_cantdeletemaindomain' => '您不能删除已分配的域。',
		'domains_canteditdomain' => '您无法编辑此域。它已被管理员禁用。',
		'domains_cantdeletedomainwithemail' => '您不能删除用作电子邮件域的域。请先删除所有电子邮件地址。',
		'firstdeleteallsubdomains' => '您必须先删除所有子域，然后才能创建一个DNS域。',
		'youhavealreadyacatchallforthisdomain' => '您已经为此域定义了一个总括。',
		'ftp_cantdeletemainaccount' => '您无法删除您的主FTP帐户',
		'login' => '您输入的用户名或密码不正确，请重新输入！',
		'login_blocked' => '此帐户已暂停，因为太多的登录错误。<br />请在%s秒后重试。',
		'notallreqfieldsorerrors' => '您没有填写全部或部分字段填写错误。',
		'oldpasswordnotcorrect' => '旧密码不正确。',
		'youcantallocatemorethanyouhave' => '你不能分配比你自己拥有的更多的资源。',
		'mustbeurl' => '您没有键入有效或完整的URL（例如http：//somedomain.com/error404.htm）',
		'invalidpath' => '你没有选择一个有效的URL（可能是目录列表有问题？）',
		'stringisempty' => '字段中缺少输入',
		'stringiswrong' => '字段输入错误',
		'newpasswordconfirmerror' => '新密码和确认不匹配',
		'mydomain' => '域名',
		'mydocumentroot' => '\'Documentroot\'',
		'loginnameexists' => '登录名%s已存在',
		'emailiswrong' => '电子邮件地址%s包含无效字符或不完整',
		'emailexists' => '电子邮件地址%s已被其他管理员使用',
		'emailexistsanon' => '电子邮件地址%s已在使用中。',
		'alternativeemailiswrong' => '要将凭据发送到的给定备用电子邮件地址%s似乎无效',
		'loginnameiswrong' => '登录名"%s"包含非法字符。',
		'loginnameiswrong2' => '登录名包含太多字符。只允许%s个字符。',
		'userpathcombinationdupe' => '用户名和路径的组合已存在',
		'patherror' => '页面不能为空！',
		'errordocpathdupe' => '路径%s的选项已存在',
		'adduserfirst' => '请先创建客户',
		'domainalreadyexists' => '域%s已分配给客户',
		'nolanguageselect' => '未选择语言。',
		'nosubjectcreate' => '您必须为此邮件模板定义一个主题。',
		'nomailbodycreate' => '必须为此邮件模板定义邮件文本。',
		'templatenotfound' => '未找到模板。',
		'alltemplatesdefined' => '您不能定义更多的模板，所有语言都已支持。',
		'wwwnotallowed' => 'www不允许用于子域名。',
		'subdomainiswrong' => '子域%s包含无效字符。',
		'domaincantbeempty' => '域名不能为空。',
		'domainexistalready' => '域%s已存在。',
		'domainisaliasorothercustomer' => '所选别名域本身就是别名域、具有不同的IP/端口组合或属于另一个客户。',
		'emailexistalready' => '电子邮件地址%s已存在。',
		'maindomainnonexist' => '主域%s不存在。',
		'maindomaindeactivated' => '主域%s已停用。',
		'destinationnonexist' => '请在“目的地”字段中创建您的货运代理。',
		'destinationalreadyexistasmail' => '到%s的转发器已作为活动电子邮件地址存在。',
		'destinationalreadyexist' => '您已经定义了到"%s"的转发器。',
		'destinationiswrong' => '转发程序%s包含无效字符或不完整。',
		'dumpfoldercannotbedocroot' => '数据转储文件夹不能是您的主目录，请在主目录中选择一个文件夹，例如/dumps',
		'templatelanguagecombodefined' => '已定义选定的语言/模板组合。',
		'templatelanguageinvalid' => '所选语言不存在',
		'ipstillhasdomains' => '您要删除的IP/端口组合仍有分配给它的域，请在删除此IP/端口组合之前将其重新分配给其他IP/端口组合。',
		'cantdeletedefaultip' => '您无法删除默认IP/端口组合，请在删除此IP/端口组合之前将另一个IP/端口组合设为默认。',
		'cantdeletesystemip' => '您无法删除最后一个系统IP，请为系统IP创建新的IP/端口组合或更改系统IP。',
		'myipaddress' => '\'IP\'',
		'myport' => '\'端口\'',
		'myipdefault' => '您需要选择应成为默认的IP/端口组合。',
		'myipnotdouble' => '此IP/端口组合已存在。',
		'admin_domain_emailsystemhostname' => 'server-hostname不能用作customer-domain。',
		'cantchangesystemip' => '您无法更改最后一个系统IP，请为系统IP创建另一个新的IP/端口组合或更改系统IP。',
		'sessiontimeoutiswrong' => '只允许数字"会话超时"。',
		'maxloginattemptsiswrong' => '只允许数字"最大登录尝试次数"。',
		'deactivatetimiswrong' => '只允许数字"停用时间"。',
		'accountprefixiswrong' => '"客户前缀"错误。',
		'mysqlprefixiswrong' => '"SQL前缀"错误。',
		'ftpprefixiswrong' => '"FTP前缀"错误。',
		'ipiswrong' => '"IP地址"错误。只允许有效的IP地址。',
		'vmailuidiswrong' => '"邮件UID"错误。只允许数字UID。',
		'vmailgidiswrong' => '"邮件GID"错误。只允许数字GID。',
		'adminmailiswrong' => '"发件人地址"错误。只允许有效的电子邮件地址。',
		'pagingiswrong' => '"每页条目数"值错误。只允许数字字符。',
		'phpmyadminiswrong' => 'phpMyAdmin-link不是有效的链接。“',
		'webmailiswrong' => 'webmail-link不是有效的链接。',
		'webftpiswrong' => 'WebFTP链接不是有效链接。',
		'stringformaterror' => '字段"%s"的值格式不正确。',
		'loginnameisusingprefix' => '您不能创建以"%s"开头的帐户，因为此前缀已设置为用于自动帐户命名。请输入其他帐户名。',
		'loginnameissystemaccount' => '帐户"%s"在系统上已存在，无法使用。请输入其他帐户名。',
		'loginnameisreservedname' => '帐户名"%s"是为系统内部保留的，无法使用。',
		'youcantdeleteyourself' => '出于安全原因，您无法删除自己。',
		'youcanteditallfieldsofyourself' => '注意：出于安全原因，您无法编辑自己帐户的所有字段。',
		'documentrootexists' => '目录"%s"已为此客户存在。请在再次添加客户之前将其删除。',
		'norepymailiswrong' => '"无回复地址"错误。只允许有效的电子邮件地址。',
		'logerror' => '日志错误：%s',
		'nomessagetosend' => '您没有输入消息。',
		'norecipientsgiven' => '您未指定任何收件人',
		'errorsendingmail' => '发送到"%s"的消息失败',
		'errorsendingmailpub' => '发送到给定电子邮件地址的消息失败',
		'cannotreaddir' => '无法读取目录"%s"',
		'invalidip' => '无效IP地址：%s',
		'invalidmysqlhost' => 'MySQL主机地址无效：%s',
		'cannotuseawstatsandwebalizeratonetime' => '您不能同时启用Webalizer和AWstats，请选择其中一个',
		'cannotwritetologfile' => '无法打开日志文件%s进行写入',
		'vmailquotawrong' => '定额必须为正数。',
		'allocatetoomuchquota' => '您尝试分配%s MB内存，但剩余内存不足。',
		'missingfields' => '未填写所有必填字段。',
		'requiredfield' => '此字段为必填字段。',
		'accountnotexisting' => '指定的电子邮件帐户不存在。',
		'nopermissionsorinvalidid' => '您没有足够的权限更改这些设置，或者提供的ID无效。',
		'phpsettingidwrong' => '此ID的PHP配置不存在',
		'descriptioninvalid' => '描述太短、太长或包含非法字符。',
		'info' => '信息',
		'filecontentnotset' => '档案不能为空！',
		'customerdoesntexist' => '您选择的客户不存在。',
		'admindoesntexist' => '您所选择的管理员不存在。',
		'ipportdoesntexist' => '您选择的IP/端口组合不存在。',
		'usernamealreadyexists' => '用户名%s已存在。',
		'plausibilitychecknotunderstood' => '无法理解可解释性检查的答案。',
		'errorwhensaving' => '保存字段%s时出错',
		'hiddenfieldvaluechanged' => '编辑设置时，隐藏字段"%s"的值发生了变化。<br /><br />这通常不是大问题，但因此无法保存设置。',
		'notrequiredpasswordlength' => '给定的密码太短。请至少输入%s个字符。',
		'overviewsettingoptionisnotavalidfield' => '哎呀，一个应该在设置概述中显示为选项的字段不是一个例外类型。你可以为此责怪开发人员。这不应该发生！',
		'pathmaynotcontaincolon' => '您输入的路径不应包含冒号(":"请输入正确的路径值。)',
		'invaliddocumentrooturl' => '请输入正确的URL或unix-path。请输入正确的URL或unix-path。',
		'exception' => '%s',
		'notrequiredpasswordcomplexity' => '不满足指定的密码复杂性。<br />如果您对复杂性规范有任何疑问，请与管理员联系',
		'invaliderrordocumentvalue' => '作为ErrorDocument给出的值似乎不是有效的文件、URL或字符串。',
		'intvaluetoolow' => '给定的数字太小（字段%s）',
		'intvaluetoohigh' => '给定的数字太高（字段%s）',
		'phpfpmstillenabled' => 'PHP-FPM当前处于活动状态。请在激活FCGID之前将其停用',
		'fcgidstillenabled' => 'FCGID当前处于活动状态。请在激活PHP-FPM之前将其停用',
		'domains_cantdeletedomainwithaliases' => '您不能删除用于别名域的域。您必须首先删除别名。',
		'user_banned' => '您的帐户已被锁定。有关详细信息，请与管理员联系。',
		'session_timeout' => '值过低',
		'session_timeout_desc' => '您不应将会话超时设置为低于1分钟。',
		'invalidhostname' => '主机名必须是有效的域。它不能为空，也不能仅由空格组成',
		'operationnotpermitted' => '不允许操作！',
		'featureisdisabled' => '功能%s已禁用。请与您的服务提供商联系。',
		'usercurrentlydeactivated' => '用户%s当前已停用',
		'setlessthanalreadyused' => '您不能设置比此用户已使用的资源少的\'%s\'资源<br />',
		'stringmustntbeempty' => '字段%s的值不能为空',
		'sslcertificateismissingprivatekey' => '您需要为证书指定私钥',
		'sslcertificatewrongdomain' => '给定的证书不属于此域',
		'sslcertificateinvalidcert' => '给定的证书内容似乎不是有效的证书',
		'sslcertificateinvalidcertkeypair' => '给定私钥不属于给定证书',
		'sslcertificateinvalidca' => '给定的CA证书数据似乎不是有效的证书',
		'sslcertificateinvalidchain' => '给定的证书链数据似乎不是有效的证书',
		'givendirnotallowed' => '不允许字段%s中的给定目录。',
		'sslredirectonlypossiblewithsslipport' => '只有当域至少分配了一个启用ssl的IP/端口组合时，才可以使用Let\'s Encrypt。',
		'fcgidstillenableddeadlock' => 'FCGID目前处于活动状态。<br />请在切换到Apache2以外的其他Web服务器之前将其停用',
		'send_report_title' => '发送错误报告',
		'send_report_desc' => '感谢您报告此错误并帮助我们改进froxlor。<br />这是将发送给froxlor开发团队的电子邮件：',
		'send_report' => '发送报告',
		'send_report_error' => '发送报告时出错：<br />%s的文件',
		'notallowedtouseaccounts' => '您的帐户不允许使用IMAP/POP 3。您无法添加电子邮件帐户。',
		'cannotdeletehostnamephpconfig' => '此PHP配置由froxlor-vhost使用，无法删除。',
		'cannotdeletedefaultphpconfig' => '此PHP配置设置为默认值，无法删除。',
		'passwordshouldnotbeusername' => '密码不应与用户名相同。',
		'no_phpinfo' => '抱歉，无法读取phpinfo（）',
		'moveofcustomerfailed' => '将客户移动到选定的管理员/代理失败。请记住，在此阶段已成功应用对客户的所有其他更改。<br><br>错误消息：%s',
		'domain_import_error' => '导入域时出现以下错误：%s',
		'fcgidandphpfpmnogoodtogether' => 'FCGID和PHP-FPM不能同时激活',
		'no_apcuinfo' => '没有可用的缓存信息。APCu似乎没有运行。',
		'no_opcacheinfo' => '没有可用的OPCache信息。OPCache似乎未加载。',
		'inactive_opcacheinfo' => 'OPCache似乎已安装但未激活。',
		'nowildcardwithletsencrypt' => 'Let\'s Encrypt无法在froxlor中使用ACME处理通配符域（需要dns-challenge），对不起。请将服务器设置为WWW或完全禁用它',
		'customized_version' => '您的froxlor安装似乎已被修改，不支持抱歉。',
		'autoupdate_0' => '未知错误',
		'autoupdate_1' => 'PHP设置allow_url_fopen被禁用。Autoupdate需要在php.ini中启用此设置',
		'autoupdate_2' => 'PHP zip扩展未找到，请确保已安装并激活',
		'autoupdate_4' => 'froxlor存档无法存储到磁盘：（',
		'autoupdate_5' => 'version.froxlor.org返回了不可接受的值：（',
		'autoupdate_6' => '哎呀，没有（有效的）版本给下载：（',
		'autoupdate_7' => '无法找到下载的存档：（',
		'autoupdate_8' => '无法解压缩存档：（',
		'autoupdate_9' => '下载的文件未通过完整性检查。请尝试再次更新。',
		'autoupdate_10' => '最低支持的PHP版本为7.4.0',
		'autoupdate_11' => 'Webupdate已禁用',
		'mailaccistobedeleted' => '当前正在删除另一个同名帐户（%s），因此此时无法添加。',
		'customerhasongoingexportjob' => '已经有一个数据导出作业等待处理，请耐心等待。',
		'exportfunctionnotenabled' => '未启用导出功能',
		'dns_domain_nodns' => '未为此域启用DNS',
		'dns_content_empty' => '没有给出内容',
		'dns_content_invalid' => 'DNS内容无效',
		'dns_arec_noipv4' => '没有给出A记录的有效IP地址',
		'dns_aaaarec_noipv6' => '没有有效的IP地址为AAA-记录给出',
		'dns_mx_prioempty' => '给定的MX优先级无效',
		'dns_mx_needdom' => 'MX内容值必须是有效的域名',
		'dns_mx_noalias' => 'MX-content值不能是CNAME条目。',
		'dns_cname_invaliddom' => 'CNAME记录的域名无效',
		'dns_cname_nomorerr' => '已存在具有相同记录名的资源记录。它不能用作CNAME。',
		'dns_other_nomorerr' => '已经存在具有相同记录名的CNAME记录。它不能用于其他类型。',
		'dns_ns_invaliddom' => 'NS记录的域名无效',
		'dns_srv_prioempty' => '给定的SRV优先级无效',
		'dns_srv_invalidcontent' => 'SRV内容无效，必须包含字段weight、port和target，例如：5 5060 sipserver.example.com。',
		'dns_srv_needdom' => 'SRV目标值必须是有效的域名',
		'dns_srv_noalias' => 'SRV-target值不能是CNAME条目。',
		'dns_duplicate_entry' => '记录已存在',
		'dns_notfoundorallowed' => '未找到或没有权限',
		'domain_nopunycode' => '您不能指定punycode（IDNA）。域名将自动转换',
		'domain_noipaddress' => '无法将IP地址添加为域',
		'dns_record_toolong' => '记录/标签最多只能包含63个字符',
		'noipportgiven' => '未提供IP/端口',
		'nosslippportgiven' => '启用SSL时，您需要选择SSL IP/端口',
		'jsonextensionnotfound' => '此功能需要php json-extension。',
		'cannotdeletesuperadmin' => '无法删除第一个管理员。',
		'no_wwwcnamae_ifwwwalias' => '无法为"www"设置CNAME记录，因为该域名已设置为生成www别名。请将设置更改为"无别名"或"通配符别名"',
		'local_group_exists' => '系统上已存在给定的组。',
		'local_group_invalid' => '给定的组名无效',
		'local_user_invalid' => '指定的用户名无效或不存在',
		'local_user_isfroxloruser' => '给定的用户名是froxlor管理的用户名，不能在此上下文中使用',
		'invaliddnsforletsencrypt' => '域DNS不包括任何选定的IP地址。无法生成Let\'s Encrypt证书。',
		'notallowedphpconfigused' => '尝试使用未分配给客户的php-config',
		'pathmustberelative' => '用户没有权限指定客户主目录以外的目录。请指定相对路径（不以/开头）。',
		'mysqlserverstillhasdbs' => '无法从客户允许列表中删除数据库服务器，因为该服务器上仍有数据库。',
		'domaincannotbeedited' => '不允许您编辑域%s',
		'invalidcronjobintervalvalue' => 'Cronjob间隔必须是以下之一：%s',
		'phpgdextensionnotavailable' => 'PHP GD扩展不可用。无法验证图像数据',
		'2fa_wrongcode' => '输入的代码无效',
		'gnupgextensionnotavailable' => 'PHP GnuPG扩展不可用。无法验证PGP公钥',
		'invalidpgppublickey' => 'PGP公钥无效',
		'invalid_validtime' => '有效时间（秒）只能介于10和120之间',
		'customerphpenabledbutnoconfig' => '客户已激活PHP，但未选择PHP配置。',
		'emaildomainstillhasaddresses' => '无法停用邮件域标志，因为此域仍有电子邮件地址。',
		'tls13requiredforhttp3' => '域http3标志已启用，但ssl协议不包括TLSv1.3',
		'senderdomainnotowned' => '给定的域名"%s"无法使用。',
		'emailhasnoaccount' => '给定的电子邮件地址"%s"没有账户，无法添加发件人地址。',
	],
	'extras' => [
		'description' => '您可以在这里添加一些额外的功能，例如目录保护。<br />每次更改后，系统都需要一些时间来应用新设置。',
		'directoryprotection_add' => '添加目录保护',
		'view_directory' => '显示目录内容',
		'pathoptions_add' => '添加路径选项',
		'directory_browsing' => '目录内容浏览',
		'pathoptions_edit' => '编辑路径选项',
		'error404path' => '404',
		'error403path' => '403',
		'error500path' => '500',
		'error401path' => '401',
		'errordocument404path' => '错误文档404',
		'errordocument403path' => '错误文档403',
		'errordocument500path' => '错误文档500',
		'errordocument401path' => '错误文档401',
		'execute_perl' => '执行Perl/CGI',
		'htpasswdauthname' => '身份验证原因（AuthName）',
		'directoryprotection_edit' => '编辑目录保护',
		'export' => '创建数据转储',
		'dump_web' => '包括Web数据',
		'dump_mail' => '包括邮件数据',
		'dump_dbs' => '包括数据库',
		'path_protection_label' => '<strong class="text-danger">重要</strong>',
		'path_protection_info' => '我们强烈建议保护给定路径，参见" extras" -> "目录保护"',
	],
	'ftp' => [
		'description' => '在这里，您可以创建和更改您的FTP帐户。<br />这些变化是即时进行的，帐户可以立即使用。',
		'account_add' => '创建帐户',
		'account_edit' => '编辑ftp帐户',
		'editpassdescription' => '设置新密码或留空不作更改。',
		'sshkey_add' => '添加ssh-key',
		'sshkey_edit' => '编辑ssh-key',
	],
	'gender' => [
		'title' => '标题',
		'male' => '先生',
		'female' => '夫人',
		'undef' => '',
	],
	'imprint' => '法律声明',
	'index' => [
		'customerdetails' => '客户详细信息',
		'accountdetails' => '账户的详细信息',
	],
	'integrity_check' => [
		'databaseCharset' => '数据库字符集（应为UTF-8）',
		'domainIpTable' => 'IP与域名引用',
		'subdomainSslRedirect' => '非SSL域的SSL重定向标志为假',
		'froxlorLocalGroupMemberForFcgidPhpFpm' => '客户组中的froxlor-user（用于FCGID/php-fpm）',
		'webserverGroupMemberForFcgidPhpFpm' => '客户组中的Webserver-user（对于FCGID/php-fpm）',
		'subdomainLetsencrypt' => '没有分配SSL端口的主域没有任何具有活动SSL重定向的子域',
	],
	'logger' => [
		'date' => '日期',
		'type' => '类型',
		'action' => '操作',
		'user' => '用户',
		'truncate' => '清空日志',
		'reseller' => '经销商',
		'admin' => '管理员',
		'cron' => 'Cronjob',
		'login' => '登录',
		'intern' => '内部',
		'unknown' => '未知',
	],
	'login' => [
		'username' => '用户名',
		'password' => '密码',
		'language' => '语言',
		'login' => '登录',
		'logout' => '注销',
		'profile_lng' => '配置文件语言',
		'welcomemsg' => '请登录以访问您的帐户。',
		'forgotpwd' => '忘记密码？',
		'presend' => '重置密码',
		'email' => '电子邮件地址',
		'remind' => '重置密码',
		'usernotfound' => '页面没有找到！',
		'backtologin' => '返回登录',
		'combination_not_found' => '未找到用户和电子邮件地址的组合。',
		'2fa' => '双重认证（2FA）',
		'2facode' => '请输入2FA代码',
		'2faremember' => '信任浏览器',
	],
	'mails' => [
		'pop_success' => [
			'mailbody' => '你好，我是\n\n您的邮件帐户{EMAIL}\n已成功建立。\n\n这是一个自动创建的\n电子邮件，请不要回答！\n\n你诚挚的，你的管理员',
			'subject' => '邮件帐户设置成功',
		],
		'createcustomer' => [
			'mailbody' => '你好{敬礼}，\n\n这是您帐户信息：\n\n用户名：{用户名}\n密码：{PASSWORD}\n\n谢谢你，\n您的管理员',
			'subject' => '账户信息',
		],
		'pop_success_alternative' => [
			'mailbody' => '你好{敬礼}，\n\n您的邮件帐户{EMAIL}\n已成功建立。\n您的密码是{PASSWORD}。\n\n这是一个自动创建的\n电子邮件，请不要回答！\n\n你诚挚的，你的管理员',
			'subject' => '邮件帐户设置成功',
		],
		'password_reset' => [
			'subject' => '密码重置',
			'mailbody' => '你好{敬礼}，\n\n这是你设置新密码的链接。2这个链接在接下来的24小时内有效。\n\n联系我们\n\n谢谢你，\n您的管理员',
		],
		'new_database_by_customer' => [
			'subject' => '[froxlor] 新建数据库',
			'mailbody' => '您好{CUST_NAME}，\n\n您刚刚添加了一个新的数据库。下面是输入的信息：\n\n数据库名称：{DB_NAME}\n密码：{DB_PASS}\n描述：{DB_DESC}\n DB主机名：{DB_SRV}\n phpMyAdmin：{PMA_URI}\n你诚挚的，你的管理员',
		],
		'new_ftpaccount_by_customer' => [
			'subject' => '新建FTP用户',
			'mailbody' => '您好{CUST_NAME}，\n\n你刚刚添加了一个新的ftp用户。下面是输入的信息：\n\n用户名：{USR_NAME}\n密码：{USR_PASS}\n路径：{USR_PATH}\n\n你诚挚的，你的管理员',
		],
		'trafficmaxpercent' => [
			'mailbody' => '亲爱的{SALUTATION}，\n\n您使用了可用{TRAFFIC}流量的{TRAFFICUSED}。\n这大于{MAX_PERCENT}%%。\n\n你诚挚的，你的管理员',
			'subject' => '达到您的流量限制',
		],
		'diskmaxpercent' => [
			'mailbody' => '亲爱的{SALUTATION}，\n\n您已使用可用{DISKAVAILABLE}磁盘空间中的{DISKUSED}。\n这大于{MAX_PERCENT}%%。\n\n你诚挚的，你的管理员',
			'subject' => '达到磁盘空间限制',
		],
		'2fa' => [
			'mailbody' => '你好，我是\n\n您的2FA登录代码是：{CODE}。\n\n这是一个自动创建的\n电子邮件，请不要回答！\n\n你诚挚的，你的管理员',
			'subject' => 'froxlor - 2FA代码',
		],
	],
	'menue' => [
		'main' => [
			'main' => '主页',
			'changepassword' => '更改密码',
			'changelanguage' => '更改语言',
			'username' => '登录名：',
			'changetheme' => '更改主题',
			'apihelp' => 'API帮助',
			'apikeys' => 'API密钥',
		],
		'email' => [
			'email' => '邮件',
			'emails' => '邮箱地址',
			'webmail' => 'Webmail',
			'emailsoverview' => '邮件域名概览',
		],
		'mysql' => [
			'mysql' => 'MySQL',
			'databases' => '数据库',
			'phpmyadmin' => 'phpMyAdmin',
		],
		'domains' => [
			'domains' => '域',
			'settings' => '域名概述',
		],
		'ftp' => [
			'ftp' => 'FTP',
			'accounts' => '账户',
			'webftp' => 'WebFTP',
			'sshkeys' => 'SSH密钥',
		],
		'extras' => [
			'extras' => '额外',
			'directoryprotection' => '目录保护',
			'pathoptions' => '路径选项',
			'export' => '数据导出',
		],
		'traffic' => [
			'traffic' => '流量',
			'current' => '当月',
			'overview' => '总流量',
		],
		'phpsettings' => [
			'maintitle' => 'PHP配置',
			'fpmdaemons' => 'PHP-FPM版本',
		],
		'logger' => [
			'logger' => '系统日志',
		],
	],
	'message' => [
		'norecipients' => '由于数据库中没有收件人，因此未发送电子邮件',
		'success' => '已成功将邮件发送给%s个收件人',
	],
	'mysql' => [
		'databasename' => '用户/数据库名称',
		'databasedescription' => '数据库描述',
		'database_create' => '创建数据库',
		'description' => '在这里，您可以创建和更改您的MySQL数据库。<br />更改立即进行，数据库可以立即使用。<br />在左侧的菜单中，您可以找到工具phpMyAdmin，使用它可以轻松管理数据库。<br /><br />要在您自己的php脚本中使用您的数据库，请使用以下设置：（斜体字的数据<i></i>必须更改为您键入的等效数据！）<br />主机名：<b><SQL_HOST></b><br />数据<b><i>库</i></b><br />密码：<b><i>您选择的密码</i></b><br />数据库：<b><i>数据库</i></b>',
		'mysql_server' => 'MySQL-Server',
		'database_edit' => '编辑数据库',
		'size' => '大小',
		'privileged_user' => '有权限的数据库用户',
		'privileged_passwd' => '特权用户的密码',
		'unprivileged_passwd' => '非特权用户的密码',
		'mysql_ssl_ca_file' => 'SSL服务器证书',
		'mysql_ssl_verify_server_certificate' => '验证SSL服务器证书',
		'globaluserinfo' => '要访问您的数据库，您还可以使用froxlor登录名（用户：%s），它可以自动访问您的所有数据库。<br />建议<b>不要</b>将其用于应用程序，仅用于管理（例如通过phpMyAdmin）。',
		'edit_global_user' => '编辑管理员用户',
	],
	'opcacheinfo' => [
		'generaltitle' => '一般信息',
		'resetcache' => '重置OPcache',
		'version' => 'OPCache版本',
		'phpversion' => 'PHP版本',
		'runtimeconf' => '运行时配置',
		'start' => '开始时间',
		'lastreset' => '上次重新启动',
		'oomrestarts' => 'OOM重启计数',
		'hashrestarts' => '哈希重启计数',
		'manualrestarts' => '手动重启计数',
		'hitsc' => '点击数',
		'missc' => '未中计数',
		'blmissc' => '黑名单小姐计数',
		'status' => '状态',
		'never' => '从未',
		'enabled' => 'OPcache已启用',
		'cachefull' => '缓存已满',
		'restartpending' => '等待重新启动',
		'restartinprogress' => '正在重新启动',
		'cachedscripts' => '缓存脚本计数',
		'memusage' => '内存使用',
		'totalmem' => '总内存',
		'usedmem' => '已用内存',
		'freemem' => '空闲内存',
		'wastedmem' => '已浪费内存',
		'maxkey' => '最大键数',
		'usedkey' => '使用的键',
		'wastedkey' => '已浪费键',
		'strinterning' => '字符串驻留',
		'strcount' => '字符串计数',
		'keystat' => '缓存密钥统计信息',
		'used' => '已用',
		'free' => '空闲',
		'blacklist' => '黑名单',
		'novalue' => '<i>无值</i>',
		'true' => '<i>真</i>',
		'false' => '<i>假</i>',
		'funcsavail' => '可用功能',
	],
	'panel' => [
		'edit' => '编辑',
		'delete' => '删除',
		'create' => '创建',
		'save' => '保存',
		'yes' => '是',
		'no' => '否',
		'emptyfornochanges' => '为空，表示没有更改',
		'emptyfordefault' => '默认值为空',
		'path' => '路径',
		'toggle' => '切换',
		'next' => '下一步',
		'dirsmissing' => '无法找到或读取目录！',
		'unlimited' => '∞',
		'urloverridespath' => 'URL（覆盖路径）',
		'pathorurl' => '路径或URL',
		'ascending' => '升序',
		'descending' => '降序',
		'search' => '搜索',
		'used' => '使用',
		'translator' => '译者',
		'reset' => '放弃更改',
		'pathDescription' => '如果该目录不存在，它将自动创建。',
		'pathDescriptionEx' => '<br /><br /><span class="text-danger">请注意：</span>由于管理设置，路径<code>/</code>不被允许，如果未设置为其他目录，它将自动设置为<code>/chosen.subdomain.tld/</code>。',
		'pathDescriptionSubdomain' => '如果该目录不存在，它将自动创建。<br /><br />如果你想重定向到另一个域，那么这个条目必须以http：//或https：//开头。<br /><br />如果URL以/结尾，则将其视为文件夹，否则将其视为文件。',
		'back' => '返回',
		'reseller' => '经销商',
		'admin' => '管理员',
		'customer' => '客户',
		'send' => '发送',
		'nosslipsavailable' => '当前没有此服务器的SSL IP/端口组合',
		'backtooverview' => '返回概览',
		'dateformat' => 'YYYY-MM-DD',
		'dateformat_function' => 'Y-m-D',
		'timeformat_function' => 'H：i：s',
		'default' => '默认',
		'never' => '从未',
		'active' => '激活',
		'please_choose' => '请选择',
		'allow_modifications' => '允许修改',
		'megabyte' => '兆字节',
		'not_supported' => '不支持：',
		'view' => '视图',
		'toomanydirs' => '子目录太多。退回到手动路径选择。',
		'abort' => '中止',
		'not_activated' => '未激活',
		'off' => '关闭',
		'options' => '选项',
		'neverloggedin' => '尚未登录',
		'descriptionerrordocument' => '可以是URL、文件路径或用""包裹的字符串<br />留空以使用服务器默认值。',
		'unlock' => '解锁',
		'theme' => '主题',
		'variable' => '可变',
		'description' => '描述',
		'cancel' => '取消',
		'ssleditor' => '此域的SSL设置',
		'ssleditor_infoshared' => '当前使用父域证书',
		'ssleditor_infoglobal' => '当前正在使用全局证书',
		'dashboard' => '仪表板',
		'assigned' => '分配',
		'available' => '可用',
		'news' => '新闻',
		'newsfeed_disabled' => '新闻源已禁用。单击编辑图标可转到设置。',
		'ftpdesc' => 'FTP描述',
		'letsencrypt' => '使用Let\'s encrypt',
		'set' => '适用',
		'shell' => 'Shell',
		'sshkeydesc' => 'SSH密钥描述',
		'ftpuser' => 'FTP用户',
		'sshpubkey' => 'SSH公钥',
		'sshpubkeyph' => "以'ssh-ed25519'、'ssh-rsa'、'ecdsa-sha2-nistp256'、'ecdsa-sha2-nistp384'、'ecdsa-sha2-nistp521'、'sk-ecdsa-sha2-nistp256@openssh.com'或'sk-ssh-ed25519@openssh.com'开头",
		'sshfingerprint' => '指纹',
		'exportpath' => [
			'title' => '导出数据的目标路径',
			'description' => '这是导出存档的存储路径。如果包含web数据，则会存储主目录中的所有文件，但不包括此处指定的文件夹。',
		],
		'export_pgp_public_key' => [
			'title' => '用于加密的公共PGP密钥',
			'description' => '这是用于加密导出的公共PGP密钥。如果您将此字段留空，则导出将不会加密。',
		],
		'pgp_public_key' => '公共PGP密钥',
		'none_value' => '无',
		'viewlogs' => '查看日志文件',
		'not_configured' => '系统尚未配置。单击此处可转到配置。',
		'start_setup' => '启动安装程序',
		'ihave_configured' => '我已经配置了服务',
		'system_is_configured' => '<i class="fa-solid fa-circle-exclamation me-1"></i>系统已设置为已配置',
		'settings_before_configuration' => '请确保在此处配置服务之前调整了设置',
		'image_field_delete' => '删除现有的当前图像',
		'usage_statistics' => '资源使用',
		'security_question' => '安全问题',
		'listing_empty' => '未找到任何条目',
		'unspecified' => '未指明',
		'settingsmode' => '模式',
		'settingsmodebasic' => '基本',
		'settingsmodeadvanced' => '高级',
		'settingsmodetoggle' => '单击以切换模式',
		'modalclose' => '关闭',
		'managetablecolumnsmodal' => [
			'title' => '管理表列',
			'description' => '在这里，您可以自定义可见列',
		],
		'mandatoryfield' => '字段为必填',
		'select_all' => '选择所有',
		'unselect_all' => '取消选择所有',
		'searchtablecolumnsmodal' => [
			'title' => '在字段中搜索',
			'description' => '选择要搜索的字段。'
		],
		'upload_import' => '上传和导入',
		'profile' => '我的个人资料',
		'use_checkbox_for_unlimited' => '值"0"将停用此资源。右侧的复选框允许"无限制"使用。',
		'use_checkbox_to_disable' => '要禁用，请激活输入字段右侧的复选框',
		'distro_mismatch' => '您似乎已升级到新的发行版。请记住相应地重新配置服务。',
		'set_new_distro' => '设置发行版',
		'dismiss' => '驳回',
	],
	'phpfpm' => [
		'vhost_httpuser' => '用于PHP-FPM的本地用户（froxlor vHost）',
		'vhost_httpgroup' => '用于PHP-FPM的本地组（froxlor vHost）',
		'ownvhost' => [
			'title' => '为froxlor vHost启用PHP-FPM',
			'description' => '如果启用，froxlor也将在本地用户下运行',
		],
		'use_mod_proxy' => [
			'title' => '使用mod_proxy / mod_proxy_fcgi',
			'description' => '<strong class="text-danger">使用Debian 9.x (Stretch)或更高版本时必须启用</strong>。激活以通过mod_proxy_fcgi使用php-fpm。需要apache-2.4.9或更高版本',
		],
		'ini_flags' => '为php.ini输入可能的<strong>php_flag</strong>。每行一个条目',
		'ini_values' => '为php.ini输入可能的<strong>php_value</strong>。每行一个条目',
		'ini_admin_flags' => '为php.ini输入可能的<strong>php_admin_flag</strong>。每行一个条目',
		'ini_admin_values' => '为php.ini输入可能的<strong>php_admin_value</strong>。每行一个条目',
	],
	'privacy' => '隐私政策',
	'pwdreminder' => [
		'success' => '已成功请求密码重置。请按照您收到的电子邮件中的说明进行操作。',
		'notallowed' => '未知用户或密码重置已被禁用',
		'changed' => '您的密码已成功更新。您现在可以使用新密码登录。',
		'wrongcode' => '抱歉，您的激活码不存在或已过期。',
		'choosenew' => '设置新密码',
	],
	'question' => [
		'question' => '安全问题',
		'admin_customer_reallydelete' => '是否确实要删除客户%s？此操作无法撤消！',
		'admin_domain_reallydelete' => '您确定要删除域名%s吗？<br><span class="text-danger"><strong>注意：</strong>与此域名关联的所有子域名、FTP账户和电子邮件地址/账户都将被删除！</span>',
		'admin_domain_reallydisablesecuritysetting' => '您真的要禁用此安全设置OpenBasedir吗？',
		'admin_admin_reallydelete' => '是否确实要删除管理员%s？每个客户和域都将重新分配给您的帐户。',
		'admin_template_reallydelete' => '是否确实要删除模板\'%s\'？',
		'domains_reallydelete' => '是否确实要删除域%s？',
		'email_reallydelete' => '确实要删除电子邮件地址%s吗？',
		'email_reallydelete_account' => '确实要删除%s的电子邮件帐户吗？',
		'email_reallydelete_forwarder' => '确实要删除转发器%s吗？',
		'email_reallydelete_sender' => '确实要删除允许的发件人%s吗？',
		'extras_reallydelete' => '确实要删除%s的目录保护吗？',
		'extras_reallydelete_pathoptions' => '确实要删除%s的路径选项吗？',
		'extras_reallydelete_export' => '是否确实要中止计划的导出作业？',
		'ftp_reallydelete' => '是否确实要删除FTP帐户%s？',
		'sshkey_reallydelete' => '你真的要删除ssh-key %s吗？',
		'mysql_reallydelete' => '是否确实要删除数据库%s？此操作无法撤消！',
		'admin_configs_reallyrebuild' => '您确定要重建所有的配置文件吗？',
		'admin_customer_alsoremovefiles' => '也删除用户文件？',
		'admin_customer_alsoremovemail' => '从文件系统中完全删除电子邮件数据？',
		'admin_customer_alsoremoveftphomedir' => '也删除FTP用户homedir？',
		'admin_ip_reallydelete' => '是否确实要删除IP地址%s？',
		'admin_domain_reallydocrootoutofcustomerroot' => '您确定要此域的文档根目录，而不是客户的客户根目录吗？',
		'admin_counters_reallyupdate' => '您确定要重新计算资源使用量吗？',
		'admin_cleartextmailpws_reallywipe' => '是否确实要从表mail_users中擦除所有未加密的邮件帐户密码？此操作无法恢复！存储未加密的电子邮件密码的设置也将设置为OFF',
		'logger_reallytruncate' => '您确定要清空表"%s"吗？',
		'admin_quotas_reallywipe' => '是否确实要擦除表mail_users上的所有配额？此操作无法恢复！',
		'admin_quotas_reallyenforce' => '您真的要对所有用户强制使用默认配额吗？这无法恢复！',
		'phpsetting_reallydelete' => '是否确实要删除这些设置？当前使用这些设置的所有域都将更改为默认配置。',
		'fpmsetting_reallydelete' => '你真的要删除这些php-fpm设置吗？所有当前使用这些设置的php配置将被更改为默认配置。',
		'customer_reallyunlock' => '您确定要解除锁定客户%s吗？',
		'admin_integritycheck_reallyfix' => '您真的要尝试自动修复所有数据库完整性问题吗？',
		'plan_reallydelete' => '是否确实要删除主机计划%s？',
		'apikey_reallydelete' => '您确定要删除此api-key吗？',
		'apikey_reallyadd' => '您确定要建立新的api-key吗？',
		'dnsentry_reallydelete' => '您确定要删除这个区域项目吗？',
		'certificate_reallydelete' => '您确定要删除此证书吗？',
		'cache_reallydelete' => '您确定要清除该高速缓存吗？',
		'please_enter_otp' => '请输入2FA代码',
		'admin_mysqlserver_reallydelete' => '您确定要删除此MySQL服务器吗？',
	],
	'redirect_desc' => [
		'rc_default' => '默认',
		'rc_movedperm' => '永久重定向 (301)',
		'rc_found' => '临时重定向 (302)',
		'rc_seeother' => '资源已移动 (303)',
		'rc_tempred' => '临时重定向 (307)',
	],
	'serversettings' => [
		'session_timeout' => [
			'title' => '会话超时',
			'description' => '在会话失效之前，用户必须处于非活动状态多长时间（秒）？',
		],
		'accountprefix' => [
			'title' => '客户前缀',
			'description' => '客户帐户应使用哪个前缀？',
		],
			'mysqlprefix' => [
				'title' => 'SQL前缀',
				'description' => 'MySQL账户应使用哪个前缀？</br>使用 "RANDOM" 作为值可获得3位随机前缀</br>使用 "DBNAME" 作为值时，数据库名字段将与客户名称一起用作前缀。',
			],
		'ftpprefix' => [
			'title' => 'FTP前缀',
			'description' => 'ftp帐户应该有哪个前缀？<br/><b>如果你改变了这一点，你也必须改变FTP服务器配置文件中的SQL查询，以防你使用它！</b>',
		],
		'documentroot_prefix' => [
			'title' => '主目录',
			'description' => '所有的主目录应该存储在哪里？',
		],
		'logfiles_directory' => [
			'title' => '日志文件目录',
			'description' => '所有日志文件都应该存储在哪里？',
		],
		'logfiles_script' => [
			'title' => '自定义脚本将日志文件传输到',
			'description' => '您可以在这里指定一个脚本，并在需要时使用占位符<strong>{LOGFILE}，{DOMAIN}和{CUSTOMER}</strong>。如果您想使用它，您还需要激活<strong>Pipe Web服务器日志文件</strong>选项。不需要前缀管道字符。',
		],
		'logfiles_format' => [
			'title' => '日志格式',
			'description' => '根据您的网络服务器规范，在此输入自定义日志格式，留空为默认值。根据您的格式，字符串必须加引号。<br/>如果与nginx一起使用，它将看起来像<i>log_format frx_custom {CONFIGURED_VALUE}</i>。<br/>如果与Apache一起使用，它将看起来像<i>LogFormat {CONFIGURED_VALUE} frx_custom</i>。<br/><strong>注意</strong>：代码不会被检查是否有任何错误。如果它包含错误，Web服务器可能无法再次启动！',
		],
		'logfiles_type' => [
			'title' => '访问日志类型',
			'description' => '在这里选择 <strong>combined</strong> 或 <strong>vhost_combined</strong>。',
		],
		'logfiles_piped' => [
			'title' => '将Web服务器日志文件传输到指定的脚本（参见上文）',
			'description' => '当使用日志文件的自定义脚本时，您需要激活它才能执行它',
		],
		'ipaddress' => [
			'title' => 'ip地址',
			'description' => '这个服务器的主IP地址是什么？',
		],
		'hostname' => [
			'title' => '主机名',
			'description' => '这台服务器的主机名是什么？',
		],
		'apachereload_command' => [
			'title' => 'Web服务器重载命令',
			'description' => '重新加载Web服务器配置文件的命令是什么？',
		],
		'bindenable' => [
			'title' => '启用域名服务器',
			'description' => '在这里可以全局启用和禁用域名服务器。',
		],
		'bindconf_directory' => [
			'title' => 'DNS服务器配置目录',
			'description' => 'DNS服务器配置文件应该保存在哪里？',
		],
		'bindreload_command' => [
			'title' => 'DNS服务器重新加载命令',
			'description' => '重新加载dns服务器守护进程的命令是什么？',
		],
		'vmail_uid' => [
			'title' => '邮件-UID',
			'description' => '邮件应该有哪个用户ID？',
		],
		'vmail_gid' => [
			'title' => '邮件-GID',
			'description' => '邮件应该使用哪个GroupID？',
		],
		'vmail_homedir' => [
			'title' => 'Mails-homedir',
			'description' => '所有邮件都应该存放在哪里？',
		],
		'adminmail' => [
			'title' => '发送者',
			'description' => '从Panel发送的电子邮件的发件人地址是什么？',
		],
		'phpmyadmin_url' => [
			'title' => 'phpMyAdmin URL',
			'description' => 'phpMyAdmin的URL是什么？（必须以http（s）：//开头）',
		],
		'webmail_url' => [
			'title' => 'Webmail URL',
			'description' => 'Webmail的URL是什么？（必须以http（s）：//开头）',
		],
		'webftp_url' => [
			'title' => 'WebFTP URL',
			'description' => 'WebFTP的URL是什么？（必须以http（s）：//开头）',
		],
		'language' => [
			'description' => '你的标准服务器语言是什么？',
		],
		'maxloginattempts' => [
			'title' => '最大登录尝试次数',
			'description' => '最大登录尝试次数，在此之后帐户将被禁用。',
		],
		'deactivatetime' => [
			'title' => '去激活时间',
			'description' => '帐户在多次登录尝试后被禁用的时间（秒）。',
		],
		'pathedit' => [
			'title' => '路径输入类型',
			'description' => '路径应该通过菜单还是通过输入字段来选择？',
		],
		'nameservers' => [
			'title' => '域名服务器',
			'description' => '一个逗号分隔的列表，包含所有域名服务器的主机名。第一个将是主服务器。',
		],
		'mxservers' => [
			'title' => 'MX服务器',
			'description' => '一个逗号分隔的列表，包含一个数字和一个主机名（用空格分隔）（例如“10 mx.example.com”），其中包含mx服务器。',
		],
		'paging' => [
			'title' => '每页条目数',
			'description' => '一页上应显示多少个条目？（0 =禁用分页）',
		],
		'defaultip' => [
			'title' => '默认IP/端口',
			'description' => '选择所有要用作新域默认值的IP地址',
		],
		'defaultsslip' => [
			'title' => '默认SSL IP/端口',
			'description' => '选择所有要用作新域默认值的启用ssl的IP地址',
		],
		'phpappendopenbasedir' => [
			'title' => '要附加到OpenBasedir的路径',
			'description' => '这些路径（用冒号分隔）将被添加到每个vHost-container中的OpenBasedir-语句中。',
		],
		'natsorting' => [
			'title' => '在列表视图中使用自然的人工排序',
			'description' => '将列表排序为web 1-> web2 -> web 11，而不是web 1-> web 11-> web2。',
		],
		'deactivateddocroot' => [
			'title' => '已停用用户的Docroot',
			'description' => '当用户被停用时，此路径将用作他的docroot。留空表示根本不创建vHost。',
		],
		'mailpwcleartext' => [
			'title' => '同时以明文形式保存邮件账户密码',
			'description' => '如果设置为是，所有密码也将以明文形式保存在 mail_users 表中（具有数据库访问权限的每个人都可读取）。只有当您打算使用 SASL 时才激活此设置！',
		],
		'ftpdomain' => [
			'title' => 'FTP帐户@domain',
			'description' => '客户可以创建FTP帐户user@customerdomain？',
		],
		'mod_fcgid' => [
			'title' => '启用FCGID',
			'description' => '使用此选项可使用相应的用户账户运行PHP。<br /><br /><b>这需要对Apache进行特殊的Web服务器配置，请参阅 <a target="_blank" href="https://docs.froxlor.org/latest/admin-guide/configuration/fcgid/">FCGID - 手册</a></b>',
			'configdir' => [
				'title' => '配置目录',
				'description' => '所有FCGID配置文件应该存储在哪里？如果您不使用自编译的suexec二进制文件（这是正常情况），此路径必须在 /var/www/ 下<br /><br /><div class="text-danger">注意：此文件夹的内容会定期删除，因此请避免手动在其中存储数据。</div>',
			],
			'tmpdir' => [
				'title' => '临时目录',
				'description' => '临时目录应该存储在哪里？',
			],
			'starter' => [
				'title' => '每个域的进程数',
				'description' => '每个域应该启动/允许多少个进程？建议使用0，因为PHP将非常有效地管理进程数量。',
			],
			'wrapper' => [
				'title' => 'VHost中的包装器',
				'description' => '包装器应如何包含在VHost中？',
			],
			'peardir' => [
				'title' => '全局PEAR目录',
				'description' => '在每个php.ini配置中应该替换哪些全局PEAR目录？不同的目录必须用冒号分隔。',
			],
			'maxrequests' => [
				'title' => '每个域的最大请求数',
				'description' => '每个域应该允许多少个请求？',
			],
			'defaultini' => '新域名的默认PHP配置',
			'defaultini_ownvhost' => 'froxlor-vHost的默认PHP配置',
			'idle_timeout' => [
				'title' => '空闲超时',
				'description' => 'Mod FastCGI的空闲超时设置。',
			],
		],
		'sendalternativemail' => [
			'title' => '使用备用电子邮件地址',
			'description' => '在创建电子邮件帐户时，将密码电子邮件发送到不同的地址',
		],
		'apacheconf_vhost' => [
			'title' => 'Web服务器vHost配置文件/目录名',
			'description' => 'vHost配置应该存储在哪里？您可以在此处指定一个文件（所有vHost都在一个文件中）或目录（每个vHost都在自己的文件中）。',
		],
		'apacheconf_diroptions' => [
			'title' => 'Web服务器目录配置文件/目录名',
			'description' => '您可以在这里指定一个文件（所有的目录都在一个文件中）或目录（每个目录都在自己的文件中）。',
		],
		'apacheconf_htpasswddir' => [
			'title' => 'Webserver htpasswd目录名',
			'description' => '用于目录保护的htpasswd文件应该存储在哪里？',
		],
		'mysql_access_host' => [
			'title' => 'MySQL访问主机',
			'description' => '一个逗号分隔的主机列表，允许用户从这些主机连接到MySQL服务器。要允许子网，网络掩码或CIDR语法有效。',
		],
		'webalizer_quiet' => [
			'title' => 'Webalizer输出',
			'description' => 'Webalizer程序的详细程度',
		],
		'logger' => [
			'enable' => '启用/禁用日志记录',
			'severity' => '日志记录级别',
			'types' => [
				'title' => '日志类型',
				'description' => '指定日志类型。若要选择多个类型，请在选择时按住Ctrl。<br />可用的日志类型有：系统日志、文件、MySQL',
			],
			'logfile' => [
				'title' => '日志文件',
				'description' => '仅在日志类型包含"文件"时使用。此文件将在froxlor/logs/中创建。此文件夹受保护，防止公共访问。',
			],
			'logcron' => 'Log cron工作',
			'logcronoption' => [
				'never' => '从未',
				'once' => '一旦',
				'always' => '总是',
			],
		],
		'ssl' => [
			'use_ssl' => [
				'title' => '启用SSL使用',
				'description' => '如果您想为您的Web服务器使用SSL，请选中此选项',
			],
			'ssl_cert_file' => [
				'title' => 'SSL证书的路径',
				'description' => '指定路径，包括.crt或.pem文件（主证书）的文件名',
			],
			'openssl_cnf' => '用于创建Cert文件的配置文件',
			'ssl_key_file' => [
				'title' => 'SSL密钥文件的路径',
				'description' => '指定路径，包括私钥文件的文件名（主要是.key）',
			],
			'ssl_ca_file' => [
				'title' => 'SSL CA证书的路径（可选）',
				'description' => '客户端身份验证，只有当你知道它是什么时才设置它。',
			],
			'ssl_cipher_list' => [
				'title' => '配置允许的SSL加密套件',
				'description' => '这是您在使用SSL时希望（或不希望）使用的加密套件列表。关于加密套件以及如何包含/排除它们，请参阅<a href="https://www.openssl.org/docs/manmaster/man1/openssl-ciphers.html">加密套件手册</a>中的"CIPHER LIST FORMAT"和"CIPHER STRINGS"部分。<br /><br /><b>默认值为：</b><pre>ECDH+AESGCM:ECDH+AES256:!aNULL:!MD5:!DSS:!DH:!AES128</pre>',
			],
			'apache24_ocsp_cache_path' => [
				'title' => 'Apache 2.4：OCSP装订缓存的路径',
				'description' => '配置用于存储包含在TLS握手中的OCSP响应的该高速缓存。',
			],
			'ssl_protocols' => [
				'title' => '配置TLS协议版本',
				'description' => '这是您在使用SSL时希望（或不希望）使用的SSL协议列表。<b>注意：</b>某些较旧的浏览器可能不支持最新的协议版本。<br /><br /><b>默认值为：</b><pre>TLSv1.2</pre>',
			],
			'tlsv13_cipher_list' => [
				'title' => '配置显式TLSv1.3加密套件（如果使用）',
				'description' => '这是您在使用TLSv1.3时希望（或不希望）使用的加密套件列表。关于加密套件以及如何包含/排除它们，请参阅<a href="https://wiki.openssl.org/index.php/TLS1.3">TLSv1.3文档</a>。<br /><br /><b>默认值为空</b>',
			],
		],
		'default_vhostconf' => [
			'title' => '默认vHost设置',
			'description' => '此字段的内容将直接包含在此ip/port vHost容器中。您可以使用以下变量：<br/><code>{域}</code>、<code>{DOCROOT}</code>、<code>{客户}</code>、<code>{IP}</code>、<code>{端口}</code>、<code>{方案}</code>、<code>{FPMSOCKET}</code>（如果适用）<br/>注意：代码不会被检查是否有任何错误。如果它包含错误，Web服务器可能无法再次启动！',
		],
		'apache_globaldiropt' => [
			'title' => '客户前缀的目录选项',
			'description' => '此字段的内容将包含在 05_froxlor_dirfix_nofcgid.conf Apache配置中。如果为空，则使用默认值：<br><br>apache >= 2.4<br><code>Require all granted<br>AllowOverride All</code><br><br>apache <= 2.2<br><code>Order allow,deny<br>allow from all</code>',
		],
		'default_vhostconf_domain' => [
			'description' => '此字段的内容将直接包含到域vHost容器中。您可以使用以下变量：<br/><code>{域}</code>、<code>{DOCROOT}</code>、<code>{客户}</code>、<code>{IP}</code>、<code>{端口}</code>、<code>{方案}</code>、<code>{FPMSOCKET}</code>（如果适用）<br/>注意：代码不会被检查是否有任何错误。如果它包含错误，Web服务器可能无法再次启动！',
		],
		'decimal_places' => '流量/网站空间输出的小数位数',
		'selfdns' => [
			'title' => '客户域dns设置',
		],
		'selfdnscustomer' => [
			'title' => '允许客户编辑域dns设置',
		],
		'unix_names' => [
			'title' => '使用UNIX兼容的用户名',
			'description' => '如果选择"否"，允许您在用户名中使用 <strong>-</strong> 和 <strong>_</strong>',
		],
		'allow_password_reset' => [
			'title' => '允许客户重置密码',
			'description' => '客户可以重置密码，激活链接将发送到他们的电子邮件地址',
		],
		'allow_password_reset_admin' => [
			'title' => '允许管理员重置密码',
			'description' => '管理员/用户可以重置密码，激活链接将发送到他们的电子邮件地址',
		],
		'mail_quota' => [
			'title' => '邮箱配额',
			'description' => '新创建邮箱的默认配额（兆字节）。',
		],
		'mail_quota_enabled' => [
			'title' => '为客户使用邮箱配额',
			'description' => '激活以在邮箱上使用配额。默认值为<b>否</b>，因为这需要特殊设置。',
			'removelink' => '单击此处清除邮件帐户的所有配额。',
			'enforcelink' => '单击此处对所有用户邮件帐户强制使用默认配额。',
		],
		'mail_enable_allow_sender' => [
			'title' => '允许客户使用"允许的发件人"',
			'description' => '如果启用，客户可以为邮件账户指定"允许的发件人"来发送邮件。<br>默认：关闭',
		],
		'mail_allow_external_domains' => [
			'title' => '允许"允许的发件人"使用外部域名',
			'description' => '如果启用，客户可以为邮件账户输入任何域名（除了本系统上不拥有的域名）作为"允许的发件人"。<br>默认：关闭',
		],
		'session_allow_multiple_login' => [
			'title' => '允许多次登录',
			'description' => '如果激活，用户可以多次登录。',
		],
		'panel_allow_domain_change_admin' => [
			'title' => '允许在管理员之间移动域',
			'description' => '如果激活，您可以在域设置中更改域的管理员。<br /><b>注意：</b>如果客户没有被分配到与域相同的管理员，则管理员可以看到该客户的所有其他域！',
		],
		'panel_allow_domain_change_customer' => [
			'title' => '允许在客户之间移动域',
			'description' => '如果激活，您可以在域名设置中更改域名的客户。<br /><b>注意：</b>froxlor将documentroot更改为新客户的默认homedir（如果激活，则+ domain-folder）',
		],
		'specialsettingsforsubdomains' => [
			'description' => '如果是，这些自定义vHost设置将被添加到所有子域;如果没有子域，则将删除特殊设置。',
		],
		'panel_password_min_length' => [
			'title' => '最小密码长度',
			'description' => '在这里您可以设置密码的最小长度。\'0\'表示：不需要最小长度。',
		],
		'system_store_index_file_subs' => [
			'title' => '将默认索引文件也存储到新目录',
			'description' => '如果启用，默认索引文件将存储到新创建的每个子域路径中（如果文件夹已经存在，则不会！）',
		],
		'adminmail_return' => [
			'title' => '答复地址',
			'description' => '将电子邮件地址定义为面板发送的邮件的回复地址。',
		],
		'adminmail_defname' => 'Panel电子邮件发件人名称',
		'stdsubdomainhost' => [
			'title' => '客户标准子域',
			'description' => '为客户创建标准子域时应使用的主机名。如果为空，则使用系统主机名。',
		],
		'awstats_path' => 'AWStats“awstats_buildstaticpages.pl”的路径',
		'awstats_conf' => 'AWStats配置路径',
		'defaultttl' => '绑定的域TTL（以秒为单位）（默认值“604800”= 1周）',
		'defaultwebsrverrhandler_enabled' => '为所有客户启用默认错误文档',
		'defaultwebsrverrhandler_err401' => [
			'title' => '401错误页面',
			'description' => '',
		],
		'defaultwebsrverrhandler_err403' => [
			'title' => '403错误页面',
			'description' => '',
		],
		'defaultwebsrverrhandler_err404' => '404错误页面',
		'defaultwebsrverrhandler_err500' => [
			'title' => '文件/URL错误500',
			'description' => '',
		],
		'ftpserver' => [
			'desc' => '如果选择了pureftpd，则会每天创建和更新用户配额的.ftpquota文件',
		],
		'customredirect_enabled' => [
			'title' => '允许客户重定向',
			'description' => '允许客户选择将被使用的重定向的http状态代码',
		],
		'customredirect_default' => [
			'title' => '默认重定向',
			'description' => '设置默认的重定向代码，如果客户没有自己设置，则应使用该代码',
		],
		'mail_also_with_mxservers' => '同时为设置了MX服务器的邮件、imap、pop3和smtp创建"A记录"',
		'froxlordirectlyviahostname' => '通过主机名直接访问froxlor',
		'panel_password_regex' => [
			'title' => '密码的正则表达式',
			'description' => '在这里，您可以设置一个正则表达式的密码复杂性。<br />空=无具体要求',
		],
		'mod_fcgid_ownvhost' => [
			'title' => '为froxlor vHost启用FCGID',
			'description' => '如果启用，froxlor也将在本地用户下运行',
		],
		'perl' => [
			'suexecworkaround' => [
				'title' => '启用SuExec解决方法',
				'description' => '仅当客户文档根不在apache suexec路径内时才启用。<br />如果启用，froxlor将生成一个从客户的perl启用目录+ /cgi-bin/到给定路径的符号链接。<br />请注意，perl将只能在文件夹cgi/cgi-bin/中工作，而不能在文件夹本身中工作（如果没有此修复，perl将工作！）',
			],
			'suexeccgipath' => [
				'title' => '客户启用Perl的目录符号链接的路径',
				'description' => '只有在启用SuExec解决方法时才需要设置此选项。<br />注意：请确保此路径位于suexec路径内，否则此解决方法将无效',
			],
		],
		'awstats_awstatspath' => 'AWStats“awstats.pl”的路径',
		'awstats_icons' => [
			'title' => 'AWstats icons文件夹的路径',
			'description' => '例如/usr/share/awstats/htdocs/icon/',
		],
		'login_domain_login' => '允许使用域登录',
		'perl_server' => [
			'title' => 'Perl服务器套接字位置',
			'description' => 'A simple guide can be found at: <a target="blank" href="https://www.nginx.com/resources/wiki/start/topics/examples/fcgiwrap/">nginx.com</a>',
		],
		'nginx_php_backend' => [
			'title' => 'Nginx PHP后端',
			'description' => '这是PHP进程监听来自nginx的请求的地方，可以是ip：port组合的unix套接字<br /> * 不使用php-fpm',
		],
		'phpreload_command' => [
			'title' => 'PHP reload命令',
			'description' => '这是用来重新加载PHP后端，如果有的话是使用<br />默认为空<br /> * 不使用php-fpm',
		],
		'phpfpm' => [
			'title' => '启用php-fpm',
			'description' => '<b>This needs a special webserver configuration see <a target="_blank" href="https://docs.froxlor.org/latest/admin-guide/configuration/php-fpm/">PHP-FPM handbook</a></b>',
		],
		'phpfpm_settings' => [
			'configdir' => 'php-fpm的配置目录',
			'aliasconfigdir' => '配置别名-php-fpm目录',
			'reload' => 'php-fpm restart命令',
			'pm' => '流程经理控制（下午）',
			'max_children' => [
				'title' => '子进程的数量',
				'description' => '当pm设置为\'static\'时要创建的子进程数和当pm设置为\'dynamic/ondemand\'时要创建的子进程的最大数<br />与PHP_FCGI_CHILDREN等效',
			],
			'start_servers' => [
				'title' => '启动时创建的子进程数',
				'description' => '注意：仅在pm设置为“dynamic”时使用',
			],
			'min_spare_servers' => [
				'title' => '所需的最小空闲服务器进程数',
				'description' => '注意：仅在pm设置为“dynamic”时使用<br />注意：当pm设置为“dynamic”时，',
			],
			'max_spare_servers' => [
				'title' => '所需的空闲服务器进程的最大数量',
				'description' => '注意：仅在pm设置为“dynamic”时使用<br />注意：当pm设置为“dynamic”时，',
			],
			'max_requests' => [
				'title' => '重生前每个孩子的请求数',
				'description' => '对于无休止的请求处理，请指定“0”。等效于PHP_FCGI_MAX_REQUESTS。',
			],
			'idle_timeout' => [
				'title' => '空闲超时',
				'description' => 'PHP FPM FastCGI的配置文件。',
			],
			'ipcdir' => [
				'title' => 'FastCGI IPC目录',
				'description' => 'php-fpm套接字将由web服务器存储的目录。<br />此目录必须对Web服务器可读',
			],
			'limit_extensions' => [
				'title' => '允许的分机',
				'description' => '限制FPM允许解析的主脚本的扩展名。这可以防止Web服务器端的配置错误。您应该只将FPM限制为.php扩展名，以防止恶意用户使用其他扩展名来执行php代码。默认值：.php',
			],
			'envpath' => '要添加到PATH环境中的路径。如果没有PATH环境变量，请留空',
			'override_fpmconfig' => '设置FPM守护程序设置（pm、max_children等）',
			'override_fpmconfig_addinfo' => '<br /><span class="text-danger">仅在"覆盖FPM守护程序设置"设置为"是"时使用</span>',
			'restart_note' => '注意：配置不会被检查是否有任何错误。如果它包含错误，PHP-FPM可能不会再次启动！',
			'custom_config' => [
				'title' => '自定义配置',
				'description' => '为每个PHP-FPM版本实例添加自定义配置，例如<i>pm.status_path = /status</i>进行监控。下面的变量可以在这里使用。<strong>注意：配置不会检查任何错误。如果包含错误，PHP-FPM可能无法重新启动！</strong>',
			],
			'allow_all_customers' => [
				'title' => '将此配置分配给所有当前现有客户',
				'description' => 'Set this to "true" if you want to assign this configuration to all currently existing customers so it can be used by them. This setting is not permanent but can be run multiple times.',
			],
		],
		'report' => [
			'report' => '启用发送有关Web和流量使用的报告',
			'webmax' => [
				'title' => 'Web空间的警告级别（百分比）',
				'description' => '有效值为0到150。将此值设置为0将禁用此报告。',
			],
			'trafficmax' => [
				'title' => '以百分比表示的流量警告级别',
				'description' => '有效值为0到150。将此值设置为0将禁用此报告。',
			],
			'report_web_bccadmin' => [
				'title' => 'BCC电子邮件，用于向管理员发送Web使用通知',
				'description' => '如果启用，则发送给客户的有关磁盘空间使用情况的警告也会发送给相应的管理员/管理员（BCC）'
			],
		],
		'dropdown' => '下拉',
		'manual' => '手动',
		'default_theme' => '默认主题',
		'validate_domain' => '验证域名',
		'diskquota_enabled' => '是否启用配额？',
		'diskquota_repquota_path' => [
			'description' => 'repquota 的路径',
		],
		'diskquota_quotatool_path' => [
			'description' => 'quotatool 的路径',
		],
		'diskquota_customer_partition' => [
			'description' => '存储客户文件的分区',
		],
		'vmail_maildirname' => [
			'title' => 'Maildir名称',
			'description' => 'Maildir目录到用户的帐户。通常是\'Maildir\'，在某些实现中是\'. maildir\'，如果留空则直接到用户的目录。',
		],
		'catchall_enabled' => [
			'title' => '使用通配符',
			'description' => '您想为您的客户提供通配符功能吗？',
		],
		'apache_24' => [
			'title' => '使用Apache 2.4的修改',
			'description' => '<strong class="text-danger">注意：</strong>仅在您实际安装了Apache 2.4或更高版本时使用<br />否则您的Web服务器将无法启动',
		],
		'nginx_fastcgiparams' => [
			'title' => 'fastcgi_params文件的路径',
			'description' => '指定nginx的fastcgi_params文件的路径，包括文件名',
		],
		'documentroot_use_default_value' => [
			'title' => '使用域名作为DocumentRoot路径的默认值',
			'description' => '如果启用并且DocumentRoot路径为空，则默认值为（子）域名。<br /><br />示例如下：<br />/var/customers/webs/customer_name/example.com/<br />/var/customers/webs/customer_name/subdomain.example.com/',
		],
		'panel_phpconfigs_hidesubdomains' => [
			'title' => '在PHP配置概览中隐藏子域',
			'description' => '如果启用，客户的子域将不会在PHP配置概览中列出，只会显示子域的数量。<br /><br />注意：只有在启用了FCGID或PHP-FPM的情况下才能看到。',
		],
		'panel_phpconfigs_hidestdsubdomain' => [
			'title' => '在PHP配置概览中隐藏标准子域',
			'description' => '如果启用，客户的标准子域将不会显示在PHP配置概览中。<br /><br />注意：只有在启用了FCGID或PHP-FPM的情况下才能看到。',
		],
		'passwordcryptfunc' => [
			'title' => '选择要使用的密码加密方法',
			'description' => '选择要使用的密码加密方法。如果更改此设置，则仅使用新方法加密新密码。现有密码不会更改。',
		],
		'systemdefault' => '系统默认',
		'panel_allow_theme_change_admin' => '允许管理员更改主题',
		'panel_allow_theme_change_customer' => '允许客户更改主题',
		'axfrservers' => [
			'title' => 'AXFR服务器',
			'description' => '允许传输（AXFR）dns区域的IP地址的逗号分隔列表。',
		],
		'powerdns_mode' => [
			'title' => 'PowerDNS操作模式',
			'description' => '如果需要DNS复制，请选择PowerDNS模式：Native for no replication（Default）/ Master。',
		],
		'customerssl_directory' => [
			'title' => 'Webserver客户SSL证书目录',
			'description' => '客户指定的SSL证书应该创建在哪里？<br /><br /><div class="text-danger">注意：此文件夹的内容会定期删除，因此请避免手动在其中存储数据。</div>',
		],
		'allow_error_report_admin' => [
			'title' => '允许管理员/经销商向froxlor报告数据库错误',
			'description' => '请注意：不要向我们发送任何个人（客户）数据！',
		],
		'allow_error_report_customer' => [
			'title' => '允许客户向froxlor报告数据库错误',
			'description' => '请注意：不要向我们发送任何个人（客户）数据！',
		],
		'mailtraffic_enabled' => [
			'title' => '分析邮件流量',
			'description' => '启用分析邮件服务器日志以计算流量',
		],
		'mdaserver' => [
			'title' => 'MDA型',
			'description' => '邮件传递服务器的类型',
		],
		'mdalog' => [
			'title' => 'MDA日志',
			'description' => '邮件传递服务器的日志文件',
		],
		'mtaserver' => [
			'title' => 'MTA类型',
			'description' => '邮件传输代理的类型',
		],
		'mtalog' => [
			'title' => 'MTA日志',
			'description' => '邮件传输代理的日志文件',
		],
		'system_cronconfig' => [
			'title' => 'Cron配置文件',
			'description' => 'cron-service配置文件的路径。froxlor将定期自动更新此文件。<br />注意：请<b>确保</b>使用与主froxlor cronjob相同的文件名（默认：/etc/cron.d/froxlor）！<br><br>如果您使用的是<b>FreeBSD</b>，请在这里指定<i>/etc/crontab</i>！',
		],
		'system_crondreload' => [
			'title' => 'Cron-daemon reload命令',
			'description' => '指定要执行的命令以重新加载系统cron-daemon',
		],
		'system_croncmdline' => [
			'title' => 'Cron执行命令（php二进制）',
			'description' => '执行cron任务的命令。仅在您知道自己在做什么时才更改此选项（默认："/usr/bin/nice -n 5 /usr/bin/php -q"）！',
		],
		'system_cron_allowautoupdate' => [
			'title' => '允许自动数据库更新',
			'description' => '<div class="text-danger"><b>注意：</b></div> 此设置允许cronjob绕过froxlor文件和数据库的版本检查，并在发生版本不匹配时运行数据库更新。<br><br><div class="text-danger">自动更新始终会为新设置或更改设置默认值。这可能并不总是适合您的系统。请在激活此选项之前三思而行</div>',
		],
		'dns_createhostnameentry' => '为系统主机名创建绑定区域/配置',
		'panel_password_alpha_lower' => [
			'title' => '小写字符',
			'description' => '密码必须至少包含一个小写字母（a-z）。',
		],
		'panel_password_alpha_upper' => [
			'title' => '大写字符',
			'description' => '密码必须包含至少一个大写字母（A-Z）。',
		],
		'panel_password_numeric' => [
			'title' => '数字',
			'description' => '密码必须包含至少一个数字（0-9）。',
		],
		'panel_password_special_char_required' => [
			'title' => '特殊字符',
			'description' => '密码必须至少包含下面定义的一个字符。',
		],
		'panel_password_special_char' => [
			'title' => '特殊字符列表',
			'description' => '如果设置了上述选项，则需要其中一个字符。',
		],
		'apache_itksupport' => [
			'title' => '使用Apache ITK-MPM的修改',
			'description' => '<strong class="text-danger">注意：</strong>仅在您启用了Apache ITK-MPM时使用<br />否则您的Web服务器将无法启动',
		],
		'letsencryptca' => [
			'title' => 'ACME环境',
			'description' => '用于Let\'s Encrypt / ZeroSSL证书的环境。',
		],
		'letsencryptchallengepath' => [
			'title' => 'Let\'s Encrypt挑战之路',
			'description' => '应通过全局别名提供Let\'s Encrypt挑战的目录。',
		],
		'letsencryptkeysize' => [
			'title' => '新Let\'s Encrypt证书的密钥大小',
			'description' => '新Let\'s Encrypt证书的密钥大小（以位为单位）。',
		],
		'letsencryptreuseold' => [
			'title' => '重新使用Let\'s Encrypt密钥',
			'description' => '如果激活，则每次续订都将使用相同的密钥，否则每次都会生成一个新密钥。',
		],
		'leenabled' => [
			'title' => '启用Let\'s Encrypt',
			'description' => '如果激活，客户可以让froxlor自动为具有ssl IP/端口的域生成和续订Let\'s Encrypt ssl证书。<br /><br />请记住，您需要通过网络服务器配置启用时，因为这个功能需要一个特殊的配置。',
		],
		'caa_entry' => [
			'title' => '生成CAA DNS记录',
			'description' => '自动为使用Let\'s Encrypt的启用SSL的域生成CAA记录',
		],
		'caa_entry_custom' => [
			'title' => '其他CAA DNS记录',
			'description' => 'DNS Certification Authority Authorization (CAA) is an Internet security policy mechanism which allows domain name holders to indicate to certificate authorities<br>whether they are authorized to issue digital certificates for a particular domain name. It does this by means of a new "CAA" Domain Name System (DNS) resource record.<br><br>The content of this field will be included into the DNS zone directly (each line results in a CAA record).<br>If Let\'s Encrypt is enabled for this domain, this entry will always be added automatically and does not need to be added manually:<br><code>0 issue "letsencrypt.org"</code> (If domain is a wildcard domain, issuewild will be used instead).<br>To enable Incident Reporting, you can add an <code>iodef</code> record. An example for sending such report to <code>me@example.com</code> would be:<br><code>0 iodef "mailto:me@example.com"</code><br><br><strong>Attention:</strong> The code won\'t be checked for any errors. If it contains errors, your CAA records might not work!',
		],
		'exportenabled' => [
			'title' => '为客户启用数据导出',
			'description' => '如果激活，客户将能够安排数据导出作业（cron-export），在其docroot中生成存档（可由客户自行选择）',
		],
		'dnseditorenable' => [
			'title' => '启用DNS编辑器',
			'description' => '允许管理员和客户管理域dns条目',
		],
		'dns_server' => [
			'title' => 'DNS服务器守护进程',
			'description' => '请记住，必须使用froxlors配置模板来配置守护进程',
		],
		'panel_customer_hide_options' => [
			'title' => '在客户面板中隐藏菜单项和流量图表',
			'description' => '选择要在客户面板中隐藏的项目。要选择多个选项，请在选择时按住Ctrl。',
		],
		'allow_allow_customer_shell' => [
			'title' => '允许客户为FTP用户启用shell访问',
			'description' => '<strong class="text-danger">请注意：Shell访问允许用户在您的系统上执行各种二进制文件。请极度谨慎地使用。如果您真的知道自己在做什么，请仅激活此选项！！！</strong>',
		],
		'available_shells' => [
			'title' => '可用外壳列表',
			'description' => '逗号分隔的shell列表，可供客户为其ftp用户选择。<br><br>请注意，默认的shell<strong>/bin/false</strong>将始终是一个选项（如果启用），即使此设置为空。它是任何情况下ftp用户的默认值。',
		],
		'le_froxlor_enabled' => [
			'title' => '为froxlor vhost启用Let\'s Encrypt',
			'description' => '如果激活，froxlor vhost将自动使用Let\'s Encrypt证书进行保护。',
		],
		'le_froxlor_redirect' => [
			'title' => '为froxlor vhost启用SSL重定向',
			'description' => '如果激活，所有对您的froxlor的http请求将被重定向到相应的SSL站点。',
		],
		'option_unavailable_websrv' => '<br><em class="text-danger">仅适用于：%s</em>',
		'option_unavailable' => '<br><em class="text-danger">由于其他设置，此选项不可用。</em>',
		'letsencryptacmeconf' => [
			'title' => 'acme.conf代码段的路径',
			'description' => '允许web服务器为acme挑战提供服务的配置片段的文件名。',
		],
		'mail_use_smtp' => '设置邮件程序以使用SMTP',
		'mail_smtp_host' => '指定SMTP服务器',
		'mail_smtp_usetls' => '启用TLS加密',
		'mail_smtp_auth' => '启用SMTP身份验证',
		'mail_smtp_port' => '要连接的TCP端口',
		'mail_smtp_user' => 'SMTP用户名',
		'mail_smtp_passwd' => 'SMTP密码',
		'http2_support' => [
			'title' => 'HTTP/2 支持',
			'description' => '为SSL启用HTTP/2支持。<br><em class="text-danger">仅在您的Web服务器支持此功能时启用（nginx 1.9.5+，apache 2.4.17+）</em>',
		],
		'http3_support' => [
			'title' => 'HTTP/3 支持',
			'description' => '为SSL启用HTTP/3支持。<br><em class="text-danger">仅在您的Web服务器支持此功能时启用（nginx 1.25.0+）</em>',
		],
		'nssextrausers' => [
			'title' => '使用 libnss-extrausers 代替 libnss-mysql',
			'description' => '不从数据库读取用户，而是从文件读取。请仅在您已经完成所需配置步骤（系统 -> libnss-extrausers）后才激活此项。<br><strong class="text-danger">仅适用于 Debian/Ubuntu（或如果您自己编译了 libnss-extrausers！）</strong>',
		],
		'le_domain_dnscheck' => [
			'title' => '使用Let\'s Encrypt时验证域名的DNS',
			'description' => '如果启用，froxlor将验证请求Let\'s Encrypt证书的域名是否解析为至少一个系统IP地址。',
		],
		'le_domain_dnscheck_resolver' => [
			'title' => '使用外部名称服务器进行DNS验证',
			'description' => '如果设置，froxlor将在使用Let\'s Encrypt时使用此DNS来验证域的DNS。如果为空，将使用系统的默认DNS解析器。',
		],
		'phpsettingsforsubdomains' => [
			'description' => '如果是，所选的php-config将被更新到所有子域',
		],
		'leapiversion' => [
			'title' => '选择Let\'s Encrypt ACME实现',
			'description' => '目前仅支持Let\'s Encrypt的ACME v2实现。',
		],
		'enable_api' => [
			'title' => '启用外部API使用',
			'description' => '为了使用froxlor API，您需要激活此选项。如需更多详细信息，请参阅 <a href="https://docs.froxlor.org/latest/api-guide/" target="_new">https://docs.froxlor.org/</a>',
		],
		'api_customer_default' => '新客户的"允许API访问"默认值',
		'dhparams_file' => [
			'title' => 'DHParams文件（Diffie-Hellman密钥交换）',
			'description' => '如果在此处指定了dhparams.pem文件，则它将包含在Web服务器配置中。保留为空将禁用。<br>例如：/etc/ssl/webserver/dhparams.pem<br><br>如果该文件不存在，则会使用以下命令自动创建该文件：<code>openssl dhparam -out /etc/ssl/webserver/dhparams.pem 4096</code>。建议在此处指定该文件之前创建该文件，因为创建过程需要相当长的时间并会阻塞cronjob。',
		],
		'errorlog_level' => [
			'title' => '错误日志级别',
			'description' => '指定错误日志级别。Apache用户的默认值是 "warn"，Nginx用户的默认值是 "error"。',
		],
		'letsencryptecc' => [
			'title' => '颁发ECC / ECDSA证书',
			'description' => '如果设置为有效密钥大小，则颁发的证书将使用ECC / ECDSA',
		],
		'froxloraliases' => [
			'title' => 'froxlor vhost的域名别名',
			'description' => '要作为服务器别名添加到froxlor vhost的域的逗号分隔列表',
		],
		'default_sslvhostconf' => [
			'title' => '默认SSL vHost设置',
			'description' => '此字段的内容将直接包含在此ip/port vHost容器中。您可以使用以下变量：<br/><code>{域}</code>、<code>{DOCROOT}</code>、<code>{客户}</code>、<code>{IP}</code>、<code>{端口}</code>、<code>{方案}</code>、<code>{FPMSOCKET}</code>（如果适用）<br/>注意：代码不会被检查是否有任何错误。如果它包含错误，Web服务器可能无法再次启动！',
		],
		'includedefault_sslvhostconf' => '在SSL-vHost中包括非SSL vHost设置',
		'apply_specialsettings_default' => '编辑域名时，"将特殊设置应用到所有子域名 (*.example.com)"设置的默认值',
		'apply_phpconfigs_default' => '编辑域名时，"将php-config应用到所有子域名"设置的默认值',
		'awstats' => [
			'logformat' => [
				'title' => 'LogFormat设置',
				'description' => '如果您为Web服务器使用了自定义日志格式，您也需要更改awstats的LogFormat。<br/>默认值为1。如需更多信息，请参阅<a target="_blank" href="https://awstats.sourceforge.io/docs/awstats_config.html#LogFormat">文档</a>。',
			],
		],
		'hide_incompatible_settings' => '隐藏不兼容的设置',
		'soaemail' => 'SOA记录中使用的邮件地址（如果为空，则默认为面板设置中的发件人地址）',
		'imprint_url' => [
			'title' => '法律的注释/印记的URL',
			'description' => '指定一个指向您的法律的注释/印记网站的URL。登录后，该链接将显示在登录屏幕和页脚上。',
		],
		'terms_url' => [
			'title' => '使用条款的URL',
			'description' => '指定一个指向您的使用条款网站的URL。登录后，该链接将在登录屏幕和页脚上显示。',
		],
		'privacy_url' => [
			'title' => '隐私政策',
			'description' => '指定您的隐私政策网站/印记网站的URL。登录时，该链接将在登录屏幕和页脚上可见。',
		],
		'logo_image_header' => [
			'title' => 'Logo图片（表头）',
			'description' => '上传您自己的徽标图像，以便在登录后显示在标题中（建议高度30px）',
		],
		'logo_image_login' => [
			'title' => 'Logo图片（登录）',
			'description' => '上传您自己的Logo图片以便在登录时显示',
		],
		'logo_overridetheme' => [
			'title' => '覆盖主题中定义的Logo（标题和登录，见下文）',
			'description' => '如果您打算使用上传的Logo，需要将其设置为"true"；或者您仍然可以使用基于主题的 "logo_custom.png" 和 "logo_custom_login.png" 方式。',
		],
		'logo_overridecustom' => [
			'title' => '覆盖主题中定义的自定义Logo（logo_custom.png 和 logo_custom_login.png）（标题和登录，见下文）',
			'description' => '如果您想忽略主题特定的自定义Logo（标题和登录）并使用"Logo图片"，请将此设置为"true"。',
		],
		'createstdsubdom_default' => [
			'title' => 'Preselected value for "Create standard subdomain" when creating a customer',
			'description' => '',
		],
		'froxlorusergroup' => [
			'title' => '所有客户用户的自定义系统组',
			'description' => '需要使用libnss-extrausers（系统设置）才能生效。空值将跳过创建或删除现有组。',
		],
		'acmeshpath' => [
			'title' => 'acme.sh 的路径',
			'description' => '将其设置为acme.sh的安装路径，包含acme.sh脚本<br>默认值为 <b>/root/.acme.sh/acme.sh</b>',
		],
		'update_channel' => [
			'title' => 'froxlor更新通道',
			'description' => '选择froxlor的更新通道。默认值为"stable"（稳定版）',
		],
		'uc_stable' => '稳定',
		'uc_testing' => '测试',
		'uc_nightly' => '每晚',
		'traffictool' => [
			'toolselect' => '流量分析器',
			'webalizer' => 'Webalizer',
			'awstats' => 'AWStats',
			'goaccess' => 'GoAccess'
		],
		'requires_reconfiguration' => '更改此设置可能需要重新配置以下服务：<br><strong>%s</strong>',
		'req_limit_per_interval' => [
			'title' => '每个时间间隔的HTTP请求数',
			'description' => '限制每个时间间隔（见下文）到froxlor的HTTP请求数，默认值为"60"',
		],
		'req_limit_interval' => [
			'title' => '速率限制间隔',
			'description' => '指定HTTP请求数的时间（秒），默认值为"60"',
		],
		'option_requires_otp' => '此设置需要OTP验证',
		'panel_menu_collapsed' => [
			'title' => '折叠菜单部分',
			'description' => '如果取消激活，左侧菜单部分将始终展开。',
		],
		'le_renew_services' => [
			'title' => '为这些服务使用froxlor Let\'s Encrypt证书',
			'description' => '如果设置为none（或下面的renew-hook命令为空），则不会对所选服务进行有关ssl的配置调整。<br><br>所选服务的reload-command应添加到renew-hook命令中，否则可能无法正确应用配置更改或更新的证书。',
		],
		'le_renew_hook' => [
			'title' => 'Let\'s Encrypt renew-hook命令',
			'description' => '将此设置为重新启动上面选择的服务的命令，以便服务正确使用续订的证书。',
		],
	],
	'spf' => [
		'use_spf' => [
			'title' => '为域名启用SPF？',
			'description' => '需要为域名配置特定的DNS条目。如果您不使用域名服务器功能，则必须手动管理这些条目。',
		],
		'spf_entry' => '所有域名的SPF条目',
	],
	'dmarc' => [
		'use_dmarc' => [
			'title' => '为域名启用DMARC？',
			'description' => '需要为域名配置特定的DNS条目。如果您不使用域名服务器功能，则必须手动管理这些条目。',
		],
		'dmarc_entry' => '所有域名的DMARC条目',
	],
	'ssl_certificates' => [
		'certificate_for' => '证书',
		'valid_from' => '有效期从',
		'valid_until' => '有效期至',
		'issuer' => '颁发者',
	],
	'success' => [
		'success' => '信息',
		'clickheretocontinue' => '点击此处继续',
		'settingssaved' => '设置已成功保存。',
		'rebuildingconfigs' => '已成功插入重新生成配置文件的任务',
		'domain_import_successfully' => '已成功导入 %s 个域名。',
		'exportscheduled' => '您的导出任务已安排。请等待处理',
		'exportaborted' => '您的计划导出已取消',
		'dns_record_added' => 'DNS记录添加成功',
		'dns_record_deleted' => 'DNS记录删除成功',
		'testmailsent' => '测试邮件发送成功',
		'settingsimported' => '设置导入成功',
		'sent_error_report' => '错误报告发送成功。感谢您的贡献。',
	],
	'tasks' => [
		'outstanding_tasks' => '待处理的cron任务',
		'REBUILD_VHOST' => '重新生成Web服务器配置',
		'CREATE_HOME' => '正在添加新客户 %s',
		'REBUILD_DNS' => '重新生成BIND配置',
		'CREATE_FTP' => '正在为新的FTP用户创建目录',
		'DELETE_CUSTOMER_FILES' => '正在删除客户文件 %s',
		'noneoutstanding' => 'froxlor目前没有待处理的任务',
		'DELETE_EMAIL_DATA' => '删除客户电子邮件数据。',
		'DELETE_FTP_DATA' => '删除客户FTP账户数据。',
		'REBUILD_RSPAMD' => '正在重新生成反垃圾邮件配置。',
		'CREATE_QUOTA' => '在文件系统上设置配额',
		'REBUILD_CRON' => '重新生成cron.d文件',
		'CREATE_CUSTOMER_DATADUMP' => '客户 %s 的数据导出任务',
		'DELETE_DOMAIN_PDNS' => '从PowerDNS数据库中删除域名 %s',
		'DELETE_DOMAIN_SSL' => '删除域名 %s 的SSL文件',
		'UPDATE_LE_SERVICES' => '更新Let\'s Encrypt的系统服务',
	],
	'terms' => '使用条款',
	'traffic' => [
		'month' => '月',
		'day' => '天',
		'months' => [
			1 => '一月',
			2 => '二月',
			3 => '三月',
			4 => '四月',
			5 => '五月',
			6 => '六月',
			7 => '七月',
			8 => '八月',
			9 => '九月',
			10 => '十月',
			11 => '十一月',
			12 => '十二月',
			'jan' => '一月',
			'feb' => '二月',
			'mar' => '三月',
			'apr' => '四月',
			'may' => '五月',
			'jun' => '六月',
			'jul' => '七月',
			'aug' => '八月',
			'sep' => '九月',
			'oct' => '十月',
			'nov' => '十一月',
			'dec' => '十二月',
			'total' => '总计',
		],
		'mb' => '流量',
		'sumtotal' => '总流量',
		'sumhttp' => 'HTTP流量',
		'sumftp' => 'FTP流量',
		'summail' => '邮件流量',
		'customer' => '客户',
		'domain' => '域名',
		'trafficoverview' => '流量概览',
		'bycustomers' => '按客户统计流量',
		'details' => '详情',
		'http' => 'HTTP',
		'ftp' => 'FTP',
		'mail' => '邮件',
		'nocustomers' => '您至少需要一位客户才能查看流量报告。',
		'top5customers' => '前5位客户',
		'nodata' => '未找到指定范围内的数据。',
		'ranges' => [
			'last24h' => '过去24小时',
			'last7d' => '过去7天',
			'last30d' => '过去30天',
			'cm' => '本月',
			'last3m' => '过去3个月',
			'last6m' => '过去6个月',
			'last12m' => '过去12个月',
			'cy' => '本年',
		],
		'byrange' => '按范围指定',
	],
	'translator' => '',
	'update' => [
		'updateinprogress_onlyadmincanlogin' => '已安装较新版本的froxlor，但尚未完成设置。<br />只有管理员才能登录并完成更新。',
		'update' => 'froxlor更新',
		'proceed' => '继续',
		'update_information' => [
			'part_a' => 'froxlor文件已更新到版本 <strong>%s</strong>。当前安装的版本为 <strong>%s</strong>。',
			'part_b' => '<br /><br />在更新完成之前，客户将无法登录。<br /><strong>继续吗？</strong>',
		],
		'noupdatesavail' => '您已经安装了froxlor的最新%s版本。',
		'description' => '为froxlor安装运行数据库更新',
		'uc_newinfo' => '有更新的%s版本可用："%s"（您当前的版本是：%s）',
		'notify_subject' => '有新的更新可用',
		'dbupdate_required' => 'froxlor文件已更新，需要更新数据库',
	],
	'usersettings' => [
		'custom_notes' => [
			'title' => '自定义备注',
			'description' => '您可以在这里自由添加任何您想要/需要的备注。它们将显示在相应用户的管理员/客户概览中。<br>支持Markdown，HTML将被移除。',
			'show' => '在用户的仪表板上显示您的备注',
		],
		'api_allowed' => [
			'title' => '允许API访问',
			'description' => '在设置中启用后，此用户可以创建API密钥并访问froxlor API',
			'notice' => '您的账户不允许访问API。',
		],
		'shell_allowed' => [
			'title' => '允许Shell访问',
			'description' => '在设置中启用后，此用户可以将Shell访问权限分配给FTP用户',
		],
		'gui_access' => [
			'title' => '允许WebUI登录',
			'description' => '禁用时，用户无法登录到froxlor Web界面，但所有服务（Web、FTP、邮件、数据库、API访问等）将正常工作。',
		],
	],
	'install' => [
		'slogan' => 'froxlor服务器管理面板',
		'preflight' => '系统检查',
		'critical_error' => '严重错误',
		'suggestions' => '非必需但建议',
		'phpinfosuccess' => '您的系统正在运行PHP %s',
		'suggestionsnote' => '没有阻止安装的严重错误，但请遵循以下建议以获得最佳体验。',
		'phpinfowarn' => '您的系统运行的PHP版本低于 %s',
		'phpinfoupdate' => '将您当前的PHP版本从%s更新到%s或更高版本',
		'start_installation' => '开始安装',
		'check_again' => '重新检查',
		'switchmode_advanced' => '显示高级选项',
		'switchmode_basic' => '隐藏高级选项',
		'dependency_check' => [
			'title' => '欢迎使用froxlor',
			'description' => '我们检查系统依赖项，以确保所有必需的PHP扩展和模块都已启用，从而确保froxlor正常运行。',
		],
		'database' => [
			'top' => '数据库',
			'title' => '创建数据库和用户',
			'description' => 'froxlor需要一个数据库，还需要一个<a href="https://docs.froxlor.org/latest/general/installation/tarball.html#_3-create-privileged-database-user" target="_blank">特权用户</a>才能创建用户和数据库（GRANT选项）。在此过程中将创建指定的数据库和非特权数据库用户。特权用户必须存在。',
			'user' => '非特权数据库用户',
			'dbname' => '数据库名称',
			'force_create' => '备份并覆盖数据库（如果存在）？',
		],
		'admin' => [
			'top' => '管理员用户',
			'title' => '让我们创建主管理员用户。',
			'description' => '该用户将被授予所有权限来调整设置以及添加/更新/删除客户、域名等资源。',
			'use_admin_email_as_sender' => '使用上面的电子邮件地址作为发件人地址。如果未选中，请在下方指定发件人地址。',
			'use_autogenerated_email_as_sender' => '留空默认为：admin@服务器名',
		],
		'system' => [
			'top' => '系统设置',
			'title' => '关于您服务器的详细信息',
			'description' => '在这里设置您的环境以及服务器相关数据和选项，让froxlor了解您的系统。这些值对于系统配置和运行至关重要。',
			'ipv4' => '主IPv4地址（如果适用）',
			'ipv6' => '主IPv6地址（如果适用）',
			'servername' => '服务器名称（FQDN，非IP地址）',
			'phpbackend' => 'PHP后端',
			'activate_newsfeed' => '启用官方新闻源<br><small>（外部来源：https://inside.froxlor.org/news/）</small>',
		],
		'install' => [
			'top' => '完成设置',
			'title' => '最后一步...',
			'description' => '根据您在安装过程中提供的数据，下面的命令将在您的系统上下载、安装和配置所需的服务。<br><br><span class="text-danger">请确保在服务器的shell/终端上以<b>root</b>身份运行以下命令，并<b>注意</b>此命令将<b>覆盖</b>任何现有配置（会创建备份）！。<br>如果您不想覆盖任何配置，请在页面底部选择<i>我将手动配置服务</i>！</span>',
			'runcmd' => '运行以下命令完成安装：',
			'manual_config' => '我将手动配置服务，只需带我到登录页面',
			'waitforconfig' => '正在等待服务配置...',
		],
		'errors' => [
			'wrong_ownership' => '确保froxlor文件属于%s：%s',
			'missing_extensions' => '以下PHP扩展是必需的，但未安装',
			'suggestedextensions' => '以下PHP扩展无法找到，但建议使用',
			'databaseexists' => '数据库已存在，请设置覆盖选项以重新生成或选择其他名称',
			'unabletocreatedb' => '无法创建测试数据库',
			'unabletodropdb' => '无法删除测试数据库',
			'mysqlusernameexists' => '为非特权用户指定的用户已存在。请使用其他用户名或先将其删除。',
			'unabletocreateuser' => '无法创建测试用户',
			'unabletodropuser' => '无法删除测试用户',
			'unabletoflushprivs' => '给定的特权用户无法刷新权限',
			'nov4andnov6ip' => '必须提供IPv4或IPv6地址',
			'servernameneedstobevalid' => '给定的服务器名称似乎不是FQDN或主机名',
			'websrvuserdoesnotexist' => '给定的Web服务器用户似乎在系统上不存在',
			'websrvgrpdoesnotexist' => '给定的Web服务器用户组似乎在系统上不存在',
			'notyetconfigured' => '似乎服务尚未配置（成功）。请运行下面显示的命令或选中复选框以稍后执行。',
			'mandatory_field_not_set' => '必填字段"%s"未设置！',
			'unexpected_database_error' => '发生意外的数据库异常。%s',
			'sql_import_failed' => '导入SQL数据失败！',
			'unprivileged_sql_connection_failed' => '初始化非特权SQL连接失败！',
			'privileged_sql_connection_failed' => '初始化特权SQL连接失败！',
			'mysqldump_backup_failed' => '无法创建数据库备份，我们从mysqldump收到一个错误。',
			'sql_backup_file_missing' => '无法创建数据库备份，备份文件不存在。',
			'backup_binary_missing' => '无法创建数据库备份，请确保已安装mysqldump。',
			'creating_configfile_failed' => '无法创建配置文件，无法写入文件。',
			'database_already_exiting' => '我们发现了一个数据库，不允许覆盖它！'
		]
	],
	'welcome' => [
		'title' => '欢迎使用froxlor！',
		'config_note' => '为了让froxlor能够与后端正常通信，您必须对其进行配置。',
		'config_now' => '立即配置'
	],
];
