#!/bin/bash
# $1 = version with dots etc.

set -e

WORKDIR=`pwd`/build

if [ -z $1 ]; then
    echo You need to specify the version to be released:
    echo "make-release 1.2.3[-rc4|-dev4|.4]"
    exit
fi

echo == Releasing version $1 ==

if [ -e $WORKDIR/$1 ]; then
	echo "-- removing old directory --"
	rm -rf $WORKDIR/$1
	echo "done"
fi
echo -n "-- making dir --"
mkdir -p $WORKDIR/$1
echo "done"

echo -n "-- cding to dir --"
cd $WORKDIR/$1
echo "done"

echo "-- cloning git repository --"
git clone git@github.com:Froxlor/Froxlor.git .
git checkout 0.10.x
echo "done"

echo "-- tagging $1 in git --"
# -s -> sign with private key
# when signing -s we need to export GPG_TTY
export GPG_TTY=`tty`
# -a -> no sign (annotated)
git tag -s $1 -m "tagging release $1"
echo "done"

echo "-- validating signed tag --"
# this needs the public key
git tag -v $1
echo "done"

echo "-- pushing tag to github --"
git push --tags
echo "done"

echo -- setting general permissions --
find -exec chmod ugo+r,u+w,go-w {} \;

echo -- setting general file permissions --
find -type f -exec chmod ugo-x {} \;

echo -- setting general directory permissions --
find -type d -exec chmod ugo+x {} \;

echo -- setting special execution permissions --
chmod 0755 install/scripts/switch-server-ip.php
chmod 0755 install/scripts/config-services.php
chmod 0755 scripts/php-sessionclean.php

echo -- remove unnecessary vcs file --
rm .gitignore

echo -- fetching composer requirements --
composer install --no-dev

##echo -- creating archives using git archive command --
##git archive --format=tar.gz --prefix=froxlor/ $1 > ../froxlor-$1.tar.gz
# zip for auto-update
##git archive --format=zip --prefix= $1 > ../froxlor-$1.zip

echo -- creating archives --
cd ..
mv $1 froxlor
# zip
cd $WORKDIR/froxlor/
zip -r froxlor-$1.zip . -x "*.git*"
mv froxlor-$1.zip ../froxlor-$1.zip
cd $WORKDIR
# tar.gz
tar -c --gzip --exclude=.git -f froxlor-$1.tar.gz froxlor
# rename back
mv froxlor $1

echo -n "-- generating checksums --"
md5sum froxlor-$1.tar.gz > froxlor-$1.tar.gz.md5
sha1sum froxlor-$1.tar.gz > froxlor-$1.tar.gz.sha1
sha256sum froxlor-$1.zip > froxlor-$1.zip.sha256
echo "-- done --"

echo -n "-- removing unused WORKDIR --"
rm -rf $WORKDIR/$1
echo "done"
